### ISSUE TITLE
Control Fit Negative

### ISSUE THREAD

**Issue by kayteeflick** [LernerLab/GuPPy#10]
When the recording is short and the signal is very pronounced, the control fit can turn up negative
![Figure_4_cfc](https://user-images.githubusercontent.com/10517323/152544631-35dc3be3-c37b-4c70-9dca-3ea0c98a9c4a.png)
.

**Comment by venus-sherathiya** [comment]
Added a fix in this [branch](https://github.com/LernerLab/GuPPy/tree/feature/betterFit)
