### ISSUE TITLE
upper bound issue 

### ISSUE THREAD

**Issue by humashaheen** [LernerLab/GuPPy#101]
![Capture](https://github.com/user-attachments/assets/af82ffe6-ddec-45c4-8084-7ae04aefecf0)

Hello,
Guppy shows this error. could anybody explain what is this about?

**Comment by humashaheen** [comment]
Yes, I get this when I try to open visualization GUI. The PSTH parameters are 5sec before the event and 15sec after, though I tired with 25 and 35 after as well but not working. only working fine with 60 seconds after.

**Comment by venus-sherathiya** [comment]
There is something very weird happening. I don't understand what it is. Can we please do a zoom call so that I can help you better ? If yes, please send me your availability at venus.sherathiya@northwestern.edu

**Comment by venus-sherathiya** [comment]
issue addressed on zoom and code updated to address it.
