### ISSUE TITLE
Struggling to add Storenames

### ISSUE THREAD

**Issue by jmnlee14** [LernerLab/GuPPy#103]
I am trying to analyze TDT Synapse data using GuPPy, and to add storenames to the Storenames GUI, I am typing "{"storenames": ["405A", "465A", "560B", "Fi1i", "Fi1r", "G-I_", "G-If", "GdF_", "MSt/", "Pu1/", "Scr/", "Tick", "U11_"], "names_for_storenames": ["control_region", "signal_region", "560B", "Fi1i", "Fi1r", "G-I_", "G-If", "GdF_", "MSt/", "Pu1/", "Scr/", "Tick", "U11_"]}" into the box below "Selected Store Names" box. Then I click the button listed as "over-write storeslist file or create a new one?" and select "create_new_file." Then a location for the file pops under "Select location of the file to over-write", so I then click Save, but no file is created in the location listed. 

I am relatively new to coding, and I am unsure what I am doing incorrectly.

**Comment by venus-sherathiya** [comment]
I think you are doing something wrong. Can we please do a zoom call so that I can help you better ? If yes, please send me your availability at venus.sherathiya@northwestern.edu.

**Comment by venus-sherathiya** [comment]
Addressed issue on zoom
