### ISSUE TITLE
storesList File Error

### ISSUE THREAD

**Issue by kaylanguyen1** [LernerLab/GuPPy#104]
I was running a TDT tank and was unable to get through step 4 due to this error. I've attached the storesList.csv names and the error. I tried changing the names to no avail. How should I fix this?

![image](https://github.com/user-attachments/assets/6fe68629-155b-4dd1-9cff-2c535e241377)
![image](https://github.com/user-attachments/assets/53fb6ad3-6d11-43a9-adb6-71511450adfa)

**Comment by venus-sherathiya** [comment]
Whatever you choose to keep in names after "_", it should be unique for different signals and same for one signal. In your case, you have one signal 465A and its isosbestic is 415A. 
So, for example, you can use :
1) "control_cal" and "signal_cal" 
or
2) "control_iso" and "signal_iso" 

Please let me know if you have any other questions or issues
