### ISSUE TITLE
Step 5 : PSTH Computation

### ISSUE THREAD

**Issue by Sundezhi1967** [LernerLab/GuPPy#105]
when run the step 5: 
ValueError: could not broadcast input array from shape (1260682) into shape (360001)
"""

The above exception was the direct cause of the following exception:

**Comment by venus-sherathiya** [comment]
Can I please see the screenshot of your storeslist.csv file and screenshot of the input parameters you are trying to use in your analysis ?

**Comment by Sundezhi1967** [comment]
![input parameters](https://github.com/user-attachments/assets/29c56c11-81c2-4c6c-926c-5f650701ad70)
![storenames](https://github.com/user-attachments/assets/21dba7eb-03b2-4201-994e-aa28ddc9dd94)
![behavior](https://github.com/user-attachments/assets/d364a376-2d65-46ed-a523-08366a8c9054)

Hi, my sampling rate is 12KHz, however, my behavior data is in different sampling rate. Is it a reason?
Besides, I use a csv file as an input. 
Thank you!

**Comment by venus-sherathiya** [comment]
Sampling rate should be same for both the data.
Can I also see the screenshot of your csv files ?
You should also follow the naming convention mentioned on left side in Storenames GUI for saving storeslist.csv file. Please refer to this [issue](https://github.com/LernerLab/GuPPy/issues/104) for a short explanation.

**Comment by venus-sherathiya** [comment]
Were you able to solve your issue ? If yes, can I close this issue ?
