### ISSUE TITLE
csv and TDT Files

### ISSUE THREAD

**Issue by kaylanguyen1** [LernerLab/GuPPy#106]
Hello,

I'm using the TDT tank as the input folder for the GUI, and I was wondering if it'd be possible to input a csv file inside the folder with the TDT tank that holds the timestamps. Additionally, would it be possible for the csv file to have timestamps framed in such a way with the first column representing the time of the start of an event and the second column representing the end time of an event? Thank you for your help, it is greatly appreciated.

**Comment by venus-sherathiya** [comment]
yes, you can input csv file for timestamps.
It should only have one column. You can make two csv files. One for start time and another for end time.

**Comment by kaylanguyen1** [comment]
Hello, we tried running a TDT tank with two csv files consisting of fake whole second timestamps like 100, 200, 300, etc. and it worked. However, when we tried running it with actual timestamps like those in the attached image, we got an error like this (attached picture of terminal). In addition, when we ran this tank and the csv files, but our graphs looked very different from when we ran our data with the fake timestamps. Is there a way we can fix this error or is it a problem with our timestamp files? 
![image](https://github.com/user-attachments/assets/61ff4d82-c9ee-4041-af9c-938acceb170a)
![image](https://github.com/user-attachments/assets/2f7f6b97-be28-472e-8788-6e7f05e1fd8c)
![image](https://github.com/user-attachments/assets/04284719-b5c0-4924-a0f8-593beac31af7)

**Comment by venus-sherathiya** [comment]
what error are you getting ? I can't see any screenshot of the terminal
and which graphs looked different ?

**Comment by kaylanguyen1** [comment]
![image](https://github.com/user-attachments/assets/8afc0963-e151-4068-9a1c-7f8d7c14f81c)
Here is the error in the terminal, apologies for not attaching it in the earlier comment. In our previous trials with the fake timestamps, the 3 plots from the image I attached in the previous comment had visible variation in their lines, compared to the above image which is almost a straight line.

**Comment by venus-sherathiya** [comment]
I think I will be able to help you better if we meet on a zoom meeting. Can you please send me your availability for next week at venus.sherathiya@northwestern.edu ?

**Comment by venus-sherathiya** [comment]
Issue addressed on zoom
