### ISSUE TITLE
GuPPy is not able to read the raw data.

### ISSUE THREAD

**Issue by jmnlee14** [LernerLab/GuPPy#107]
Following the steps as shown on YouTube, I am stuck on reading the raw data. After selecting the proper storenames, adjusting the settings and saving, I click on Read Raw Data and receive this error message in Terminal, "Read progress bar increment values function started...
python: can't open file '/Volumes/JML Data/FP on the EZM/GuPPy-main/GuPPy/GuPPy/readTevTsq.py': [Errno 2] No such file or directory"

Thank you in advance for any help!

**Comment by venus-sherathiya** [comment]
Launching of GuPPy was not done properly. Addressed issue on zoom
