### ISSUE TITLE
peak analysis for peri-event

### ISSUE THREAD

**Issue by danaconlisk** [LernerLab/GuPPy#13]
Hi! guppy is a really great tool but I was wondering if you guys were planning on implementing peak amplitude/frequency analysis for events? could be interesting for us but unfortunately it is not offered with guppy

**Comment by venus-sherathiya** [comment]
How do you want the peak amplitudes and frequency in PSTHs ?

**Comment by danaconlisk** [comment]
First and most important, how the frequency of transients change as a consequence of the presentation of a discriminative stimulus change (essentially, transient freq during the presentation of a signal that tells the animal to inhibit behavior(pre) vs during the presentation of a signal that tells the animal it should behave(post)). And the same for the avg amplitude pre and post event..
Essentially as I understand we can only look at the peak and AUC for psths and the freq/avg amplitude for the whole recording at the moment. but if the recording is consisted of multiple trials, the extraction of amplitude/freq isnt really helpful. Ideally it would be extracted as it is with AUC/peak but with transient freq/amplitude pre/post event for the desired time period indicated in the PSTH section, so we could average them over multiple trials and then proceed with stats.
hope that was clear. sorry i didnt really understand what you were asking
thanks for the quick reply :)
D

**Comment by venus-sherathiya** [comment]
For now, you can achieve it by writing a small piece of code using any programming language you are comfortable with.

When you run the whole analysis, you will see file name called 'transientOccurences...'
It is a csv file and it has timestamps at which transients were detected and also the corresponding amplitude.
You can read transientOccurences csv file in a code, use the event timestamps file and extract the values from the csv pre-event and post event.

If it is very urgent for you, you can try to implement a small code using the approach I mentioned.

I will also try to implement what you mentioned in GuPPy but I will need some time.
Thank you !!

**Comment by danaconlisk** [comment]
Great thanks a lot!
