### ISSUE TITLE
Clarification on input parameter - 'Number of channels (Neurophotometrics only)'

### ISSUE THREAD

**Issue by nirvikara** [LernerLab/GuPPy#15]
I am asking this here because the wiki page does not clarify this.  Can you please explain what exactly is the input parameter - 'Number of channels (Neurophotometrics only)?'  
I understand that it should be the number of channels used while recording, when data files has **no column names mentioning “Flags” or “LedState”**. I am wondering what to enter if my Neurophometrics data file has a "LedState" column? Does it override any entry and decides number of channel based on "LedState" column?

**Comment by venus-sherathiya** [comment]
If you already have "LedState" column in your file, don't use parameter "Number of channels (Neurophotometrics only)". Just keep that value as it is without changing (it won't affect the analysis process at all)
Also, you opened an issue before. Was it solved or you need any help with it ?
