### ISSUE TITLE
Flow diagram of GuPPy trace processing

### ISSUE THREAD

**Issue by matiasandina** [LernerLab/GuPPy#16]
Hello,
I am doing a bit of analysis to make comparisons between different methods for fiber photometry analysis. I have noticed all methods are all very similar but with slightly different flavors. There is also more than one option on each pipeline.
You have some hints on the wiki, and there's a figure on the paper with the traces, but I was wondering if you had a diagram or something sequential, closer to code with the parameter values, so that I can implement the same functions in the repo outside GuPPy to compare pipelines.
If not, I am happy to make one but I would need a bit of help with the order of function calls :smile: !

**Comment by venus-sherathiya** [comment]
Just for more clarity, are you talking about methods used in "Step 4 : Extract timestamps and its correction" ?
if not, can you please tell me which different methods you are talking about ?

**Comment by venus-sherathiya** [comment]
Sorry for late reply !! Please try to look at "extractTsAndSignal" function in preprocess.py file. It's very easy to follow.
Let me know if you find hard to get it, I will try to give you more details.
