### ISSUE TITLE
NO storename found in Neurophotometric file

### ISSUE THREAD

**Issue by mscard** [LernerLab/GuPPy#18]
Hi,
thank you so much for this amazing tool. I'm just getting started and wanted to play with my Neurophotometric data to compare Guppy with Matlab pipeline...but getting stuck at the very beginning!! I am attaching screenshots of my NPM .csv file (I'm recording both green and red channels in both hemispheres, so 4 channels total) and the ALERT note I get when trying to assign names to storenames. Any help will be greatly appreciated!
<img width="1385" alt="Screen Shot 2022-04-26 at 11 09 01 AM" src="https://user-images.githubusercontent.com/103960256/165345644-72970a60-d101-45a4-8a79-dff607c592e3.png">
<img width="941" alt="Screen Shot 2022-04-26 at 11 15 11 AM" src="https://user-images.githubusercontent.com/103960256/165345764-54373e6d-3aae-4cf8-99cc-8815a39cb134.png">

**Comment by venus-sherathiya** [comment]
Replied on gitter chat
