### ISSUE TITLE
time correction file does not exist+bokeh error

### ISSUE THREAD

**Issue by CeliaRais** [LernerLab/GuPPy#19]
Hello,
Thank you for this great tool! I have been trying to implement it with my data, but I am getting an error message that I am not able to interpret. Everything works fine up to the "Extract timestamps and apply corrections" step, where I get the error message that you can see below in the attached files. 

![bokeh error (2)](https://user-images.githubusercontent.com/104625479/165927621-bded0811-88f0-4329-b68f-d34ef41880fb.png)
![bokeh error2](https://user-images.githubusercontent.com/104625479/165927771-1e04d036-ebb4-4582-a4d4-bd8e180a8acd.png)
![bokeh error 3](https://user-images.githubusercontent.com/104625479/165927829-1c2c5fc4-c167-4434-a4dd-51ba9df03455.png)

When I look at the output folder, the time correction file is called  "timeCorrection_CeA.hdf5" (CeA being the region name that I used in the storenames) and not "timeCorrection_channel.hdf5", but this is the same name I get when I do the exact same analysis with the sample data, which works perfectly well until the end. So I am a bit at a loss as to what could have gone wrong.

I am also attaching my csv files, I tried to make them as similar to the sample data as possible but I might have missed something.

![signal channel](https://user-images.githubusercontent.com/104625479/165941077-c7e32594-2364-4e19-a14f-c4cc1cc710b9.png)
![control channel](https://user-images.githubusercontent.com/104625479/165941099-608c30cd-daab-42bb-ab9d-28db6665edc2.png)
![TTL](https://user-images.githubusercontent.com/104625479/165941537-68cef56d-17a7-4ecd-a377-643b11bec98d.png)

Thank you in advance for your help!

Best Regards,

Celia

**Comment by venus-sherathiya** [comment]
First of all, your timestamps should start from zero.
Also, may I see the screenshot of your storeslist.csv file and inputParameters.json file ?

**Comment by CeliaRais** [comment]
The Timestamps are the ones I get from Bonsai, which uses the absolute time of the Neurophotometrics system instead of starting at 0 for each recording, is it important that they both start at 0 for the analysis or do they just need to be consistent within one recording session? (I could change that parameter for future recordings if necessary). I tried to modify this in my files just now and still got the same error message.

I have attached both files below

![storeslist](https://user-images.githubusercontent.com/104625479/166436340-01a72257-517a-4ae1-bf69-aa8e24632bee.png)
![input parameters](https://user-images.githubusercontent.com/104625479/166436392-072925db-208d-4826-854a-4092b8740577.png)

**Comment by venus-sherathiya** [comment]
Try not to use control and channel in both the rows while saving storeslist.csv file.
So, in your case, just rename your files and use names other than "control" and "signal" in it.
Also, I think it should not matter if your timestamps do not start from 0.
Let me know what you get after doing changes in the storeslist file

**Comment by CeliaRais** [comment]
I renamed the files 410 and 470 instead of control_channel and signal_channel and it worked! Thank you for your help!

**Comment by venus-sherathiya** [comment]
Awesome !! Please reach out to me if you have any other problems in future. Closing this issue now.
