### ISSUE TITLE
Link to Sample Data broken

### ISSUE THREAD

**Issue by candymountain** [LernerLab/GuPPy#20]
Dear Lerner lab,

Firstly thank you so much for putting this resource on github. I believe I have successfully installed Guppy but I have a hurdle in that I don't have access to the "sample data" so not sure how I should format my csv. Any assistance at your next availability would be greatly appreciated.

**Comment by outlace** [comment]
Also having this issue

**Comment by venus-sherathiya** [comment]
Sorry for the inconvenience. Updated the link. You can now access the sample data. 
We wanted to put all the sample data together and data size is big. So, we decided to use the cloud and shared the link

**Comment by candymountain** [comment]
Dear Venus. Box is still telling me the link is broken or unavailable to me. Out of curiosity am I required to have a box account to access the sample data example?

**Comment by venus-sherathiya** [comment]
it's should work now. It's not on box anymore. when you click on Sample Data on read me file, what do you get ?

**Comment by venus-sherathiya** [comment]
I fixed the link in wiki too. Thanks for letting me know !!
