### ISSUE TITLE
Could not parse explicit URL

### ISSUE THREAD

**Issue by nschapp** [LernerLab/GuPPy#21]
Hello Lerner Lab

I was recommended GuPPy by another lab who is using fiber photometry, but I have had some issues with the installation.  I've tried installing GuPPy on two different Windows devices, but I have had the same error on both attempts when trying to create the guppy env.  Upon executing the initial command "conda create --name guppy --file spec_file_windows10.txt" in the C:\Users\MyUsername\Desktop\GuPPy-main folder where the files are held, I get this parsing error:

ParseError: Could not parse explicit URL: https://repo.anaconda.com/pkgs/main/win-64/blas-1.0-mkl.conda

It seems to be hung up on the initial URL in the spec_file_windows10.txt file.  I'm not sure if this is an issue on Anaconda's end in how I might have it set up, or an issue consistent with both of my computers.  If you would happen to know what causes this issue I would greatly appreciate the feedback.

Nick

**Comment by venus-sherathiya** [comment]
does this command throw any error on the screen ? if yes, may I please see the full screenshot of it ?

**Comment by nschapp** [comment]
<img width="657" alt="2022-05-09 15_12_24-Select Administrator_ Anaconda Prompt" src="https://user-images.githubusercontent.com/69989544/167480899-5a512dbb-7531-4165-93bb-41e785ccea56.png">

That just causes the next line to forward the same error, as seen here.

**Comment by nschapp** [comment]
According to the command prompt I am running conda 4.5.12

**Comment by venus-sherathiya** [comment]
I think I know what's the problem
let me run few tests and I will get back to you asap

**Comment by venus-sherathiya** [comment]
can you try to update conda using the command below ?
`conda update conda`
and then try to run the command
`conda create --name guppy --file spec_file_windows10.txt`

**Comment by venus-sherathiya** [comment]
glad to know that. Please reach out to me if you have any questions in the future !!
