### ISSUE TITLE
Storenames GUI with CSVs

### ISSUE THREAD

**Issue by jrosh** [LernerLab/GuPPy#23]
Hi, thanks for taking the time to make this tool for photometry analysis. I'm using a Doric system so all of my files are saved as CSVs in the format specified. I was following along in the Youtube video you made for working with CSVs and I keep getting stuck on the "Storenames GUI" step. I have 12 files in my folder with unique names but when I click on the "Open Storenames GUI" none of my file names show up in the selection box -- instead it repeats "chev1, chev2, chev3, chod1, chod2, chod3" 12 times and now there are an additional 6 files named "chev1, chev2, chev3, chod1, chod2, chod3" in the folder I'm trying to analyze. Any idea why this is happening?
![image](https://user-images.githubusercontent.com/50154808/181351224-c7d580c4-a650-4643-9ba6-0a27cf332d38.png)
![image](https://user-images.githubusercontent.com/50154808/181351284-fcc96053-1f72-460e-9705-e7904b176b3c.png)

**Comment by venus-sherathiya** [comment]
sorry for late reply !!

open your csv file in any  text editor and can you please send me the screenshot of your opened csv file ?

**Comment by jrosh** [comment]
Please see the attached screenshot.
![image](https://user-images.githubusercontent.com/50154808/182893676-9585c42b-0ecb-4119-ba54-5bf80ae595a0.png)

**Comment by venus-sherathiya** [comment]
so you are getting problems with your data or sample data ?
I am asking because you sent me a screenshot of sample data

**Comment by jrosh** [comment]
My mistake, I took a screenshot from the wrong GuPPy folder. Please see attached for an example of my data.
![image](https://user-images.githubusercontent.com/50154808/182895348-556e0c74-82f5-435b-9992-ff3d1772e15b.png)

**Comment by venus-sherathiya** [comment]
in this case, if you look closely there are four columns
there should be exact three columns otherwise it will work differently
so get rid of the first column which has just index numbers like 0,1,2,3,4,5,...
please let me know if it works or not

**Comment by jrosh** [comment]
I did not catch that! I exported csvs using pandas and forgot it includes indices by default. I will try again with the indices removed. Thanks for pointing that out. I will let you know later today if that solved my problem.

**Comment by venus-sherathiya** [comment]
sure !! please let me know

**Comment by jrosh** [comment]
Hi, I was able to resolve the Storenames GUI problem by removing the indices from my raw csv files. Thank you for your help! I will try and make my way through the rest of the steps. Hopefully I will not encounter any more problems.
