### ISSUE TITLE
PSTH Computation Error Message

### ISSUE THREAD

**Issue by jamiecm17** [LernerLab/GuPPy#26]
I keep running into an issue during PSTH computation where the program throws the following error: "ValueError: could not broadcast input array from shape (1956940) into shape (1981)" (see image 1 below)

This results in the required files for PSTH analysis and visualization not being created, so I can't proceed to the visualization step ("beep_VTA_z_score_VTA.h5 does not exist") (see image 2 below). What is causing this error? The rest of the steps seem to work just fine.

Image 1
![image](https://user-images.githubusercontent.com/92749734/199812371-0be96b68-ae3a-4c41-afd3-ae462a2095be.png)

Image 2
![image](https://user-images.githubusercontent.com/92749734/199812989-a0a2f03a-ed8f-49df-9366-0a4fb169f836.png)

**Comment by jamiecm17** [comment]
never mind it was an error on my part. please disregard.

**Comment by Jiachen24** [comment]
Hi! I have the same error in computing PSTH. May I know how did you fix it?
