### ISSUE TITLE
Error at "extract timestamps and its corrections"

### ISSUE THREAD

**Issue by samcentanni** [LernerLab/GuPPy#3]
First, love the preprint and excited to play around with this. I think its a great resource.

Preface: using TDT GCaMP data with 405 and 470 channel and csv files with behavioral timepoints (in seconds). Running the gui on Ubuntu 18.04. When I get to the "extract timestamps and its corrections" section, i'm getting a type error: cannot use a string pattern on a bytes-like object. Here is the full error:
"Computing z-score for each of the data...
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f90adfec470>>, <Task finished coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at /home/samuel/anaconda3/envs/guppy/lib/python3.6/site-packages/bokeh/server/session.py:51> exception=TypeError('cannot use a string pattern on a bytes-like object',)>)"

Note: this is occurring with the sample data as well.

**Comment by venus-sherathiya** [comment]
happy to help !! Can I see your csv file screenshot, inputParameters file screenshot and storesList file screenshot ?

**Comment by venus-sherathiya** [comment]
> First, love the preprint and excited to play around with this. I think its a great resource.
> 
> Preface: using TDT GCaMP data with 405 and 470 channel and csv files with behavioral timepoints (in seconds). Running the gui on Ubuntu 18.04. When I get to the "extract timestamps and its corrections" section, i'm getting a type error: cannot use a string pattern on a bytes-like object. Here is the full error:
> "Computing z-score for each of the data...
> tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f90adfec470>>, <Task finished coro=<_needs_document_lock.._needs_document_lock_wrapper() done, defined at /home/samuel/anaconda3/envs/guppy/lib/python3.6/site-packages/bokeh/server/session.py:51> exception=TypeError('cannot use a string pattern on a bytes-like object',)>)"
> 
> Note: this is occurring with the sample data as well.

happy to help !! Can I see your csv file screenshot, inputParameters file screenshot and storesList file screenshot ?

**Comment by samcentanni** [comment]
![Screen Shot 2021-08-10 at 5 54 06 PM](https://user-images.githubusercontent.com/63464831/128945230-5e9b5f83-3bf7-4f19-8c2a-2e493838c9f3.png)
![Screen Shot 2021-08-10 at 5 52 40 PM](https://user-images.githubusercontent.com/63464831/128945232-f3f6d83c-370c-4e5b-8026-8126647e4739.png)
![Screen Shot 2021-08-10 at 5 50 38 PM](https://user-images.githubusercontent.com/63464831/128945233-0e18a7c5-e02d-4935-b6ba-2fd5ef4aed0f.png)

**Comment by venus-sherathiya** [comment]
you have selected all the files in the folder SubjectV1_RS. Don't do that.
Just select the whole folder where your data is located in the input parameters GUI (Not individual files)

For storeslist file, when you save storenames please follow the instructions given in the Storenames GUI
For example, in your case you have selected 405A, 470A, head_only_mvmt_start_times, whole_body_start_times, tall_mvmt_start_times
the names for these storenames should be like control_X, signal_X, head_only, whole_body_only, tall_only, 
where X can be anything which is relevant for the data (for example X can be the region name where you have recorded your data like DMS or something else)

For event timestamps csv file, try to name the column as 'timestamps' (all lower case just like it is shown in the sample data)

Please make these changes and run the analysis again. If you didn't understand it ask me again. Also, if you come across any problems after following these instructions please let me know.

**Comment by samcentanni** [comment]
![Screen Shot 2021-08-10 at 6 22 23 PM](https://user-images.githubusercontent.com/63464831/128947182-e0173e66-509f-4b6e-a66e-296355662569.png)
sorry that was my first attempt. I did correct that for the attempt where I got the error above. I will make the other change to timestamp now

**Comment by venus-sherathiya** [comment]
yes !! this seems right.

**Comment by samcentanni** [comment]
Yeah that didnt fix anything. I think it is something upstream in step 3. Getting this error.
![Screen Shot 2021-08-10 at 7 29 34 PM](https://user-images.githubusercontent.com/63464831/128951884-38b7d9b6-8e92-4e06-ac64-1df5c98f2bae.png)

**Comment by venus-sherathiya** [comment]
Actually, it is not an error. Step 3 worked well. 
You will see the hdf5 files for each storenames in the output folder after running step 3.
are you getting the same error as before in step 'extract timestamps and its correction' ?

**Comment by samcentanni** [comment]
yes and I will add that these same errors are happening with the practice data provided
![Screen Shot 2021-08-10 at 7 37 03 PM](https://user-images.githubusercontent.com/63464831/128952336-ed505210-367a-4b43-8af9-21472e8b55fd.png)
![Screen Shot 2021-08-10 at 7 36 30 PM](https://user-images.githubusercontent.com/63464831/128952343-a5044585-1ac8-459f-b6ee-2d6ad5e5e47d.png)

**Comment by venus-sherathiya** [comment]
lets do one thing. Can we do a zoom call tomorrow to help you solve this error ?
please email me on my email id venus.sherathiya@northwestern.edu with your available times.
