### ISSUE TITLE
can't open .doric file

### ISSUE THREAD

**Issue by wenyu-ding** [LernerLab/GuPPy#36]
Hi,

I download the Guppy-1.2.0, which says to support the .doric file. 
when I went to "open Storenames GUI", there was an error (see the picture)
![image](https://user-images.githubusercontent.com/77887179/228676981-f55e7a41-9cb9-4674-9791-c198d2a2e6a2.png)
also, see my .doric file in the "Input Parameters GUI"
![image](https://user-images.githubusercontent.com/77887179/228677426-4fa1c35e-c38a-48fb-89b3-90353920f45c.png)
Would you happen to have any idea about this?

**Comment by venus-sherathiya** [comment]
so you have two different recordings for saline injection and LiCl injection, right ?

**Comment by wenyu-ding** [comment]
Yes! Sent from Mail for Windows From: Venus SherathiyaSent: Thursday, March 30, 2023 6:52 PMTo: LernerLab/GuPPyCc: Wenyu Ding; AuthorSubject: Re: [LernerLab/GuPPy] can't open .doric file (Issue #36) so you have two different recordings for saline injection and LiCl injection, right ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by venus-sherathiya** [comment]
yes, you can compare !!
Also, I can only see one file which is saline_0001.doric

**Comment by wenyu-ding** [comment]
Cool! How can I do that? I sent you two links. The below one is LiCl. I sent it again.https://www.dropbox.com/s/lp7sh95tprxingy/LiCl_0001.doric?dl=0 Sent from Mail for Windows From: Venus SherathiyaSent: Thursday, March 30, 2023 6:54 PMTo: LernerLab/GuPPyCc: Wenyu Ding; AuthorSubject: Re: [LernerLab/GuPPy] can't open .doric file (Issue #36) yes, you can compare !!Also, I can only see one file which is saline_0001.doric—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by venus-sherathiya** [comment]
thank you !!
Your link got attached thats why
I got it now !!

**Comment by wenyu-ding** [comment]
Great!Let me know if them work. Thank you! Sent from Mail for Windows From: Venus SherathiyaSent: Thursday, March 30, 2023 6:57 PMTo: LernerLab/GuPPyCc: Wenyu Ding; AuthorSubject: Re: [LernerLab/GuPPy] can't open .doric file (Issue #36) thank you !!Your link got attached thats whyI got it now !!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by wenyu-ding** [comment]
Hello, did you solve the issue for the new version .doric files. I have converted my doric file into .csv files, but they are still not working. In addition, can you explain a bit how to compare the signal between two recording, like the saline and LiCl group? Thanks for your help!

**Comment by venus-sherathiya** [comment]
why are they not working ?
what's the issue ?

I am working on adding support for the new version of .doric 
I will get it done by next week

**Comment by wenyu-ding** [comment]
Great! I'm looking forward to it. 
I even tried your .csv sample data, but when I read the raw data, there was the following error:
![image](https://user-images.githubusercontent.com/77887179/231877295-2389bb5c-1702-48dd-ae65-a040d346f9ed.png)
do you know why this happened? Thank you so much!

**Comment by wenyu-ding** [comment]
Hello, did you fix the problem to load .doric V6 file? thanks!

**Comment by venus-sherathiya** [comment]
I am so sorry for the delay. I am juggling between few things now. I am still working on it. Please give me 2-3 days and it will be done.
Are you still getting the above error you mentioned ?

**Comment by oradomskyi** [comment]
Hello, I'm Alex from EMBL Rome

We just got a new Doric system with 405nm(isosbestic) and 465nm(excitation for GCaMP) LEDs and getting sort of *.doric(essentially just an *.hdf5) data from Doric Neuroscience Studio v6.2.4.0.

Would you please give an advice on how to convert this data into a GuPPy-readable format?

Thanks a lot!

The original doric file and some more info here in my gdrive:

https://drive.google.com/drive/folders/1izzcKtBIjy7IxGt3E2AVeHHzvqFAzB3N?usp=sharing

AIN01 - modulated(Lock-In) raw input, 405nm constant intensity sine at about 206Hz and 465nm also constant intensity sine at about 512Hz
AIN01xAOUT01-LockIn - demodulated isosbestic signal
AIN01xAOUT02-LockIn - demodulated GCaMP signal
 
![image](https://github.com/LernerLab/GuPPy/assets/15631226/5148eb5b-dfba-4d46-9268-8d00558a2b82)
![image](https://github.com/LernerLab/GuPPy/assets/15631226/8ec9e0a9-8c0f-4103-a4a5-abb573b0a100)

**Comment by venus-sherathiya** [comment]
you can use the updated GuPPy from [branch](https://github.com/LernerLab/GuPPy/tree/feature/betterGUPPy) so that you can use updated .doric files in GuPPY. Follow all the instructions properly because it has changed little bit

**Comment by venus-sherathiya** [comment]
It is resolved !!
