### ISSUE TITLE
Please help super beginner!

### ISSUE THREAD

**Issue by gyujinea5** [LernerLab/GuPPy#37]
![image](https://user-images.githubusercontent.com/87831983/229265204-b330afd7-812e-4fca-8fca-25a6a1a2039e.png)

I am super beginner for this and take whole day for one step!
I can see this ERROR and try to change name as under bar, number, shortly..

But still can see same problem. 
Could you let me know how to fix this?

**Comment by venus-sherathiya** [comment]
Can I please see the screenshot of your stores list.csv file (which gets saved in output folder) ?

**Comment by gyujinea5** [comment]
Thanks for helping me!
Sure, the file is saved at here. 

![image](https://user-images.githubusercontent.com/87831983/229598890-bbb3c463-1498-499a-b848-c7789e409c1a.png)

**Comment by venus-sherathiya** [comment]
there should be a storeslist.csv file inside "GP_test_230329_104803_output_1" folder.
Can I please see the screenhot of the contents of storeslist.csv file ?

**Comment by gyujinea5** [comment]
oh, I see. 

![image](https://user-images.githubusercontent.com/87831983/230399284-06b5930d-d16e-49eb-9ad2-753883ab6011.png)

 and inside of csv is this. 

![image](https://user-images.githubusercontent.com/87831983/230399572-9b51b401-f90a-4478-806d-2c2f501c88f6.png)


Thank you so much for helping me!

**Comment by venus-sherathiya** [comment]
your control and signal should have same identifier
for example, if I have one control and signal (it applies to you also)
I will use same identifier for both, example : control_DMS and signal_DMS
if you have two controls and signals
it will be something like this : control_DMS, signal_DMS and control_DLS, signal_DLS

**Comment by venus-sherathiya** [comment]
were you able to fix your error ?

**Comment by venus-sherathiya** [comment]
lets try to do a zoom call any time this week to solve your problem
email me at venus.sherathiya@northwestern.edu with your availability this week.
