### ISSUE TITLE
Cannot open CSV file

### ISSUE THREAD

**Issue by zova137** [LernerLab/GuPPy#38]
Hi,

I converted my doric files using the format conventions you mentioned in the youtube video but still, storenames GUI doesn't know them 
(Alert !!
No storenames found. There are not any TDT files or CSV files to look for storenames.)

In video, you also opened a folder which is impossible for me, as it only open storenames window if I open CSV files.

**Comment by venus-sherathiya** [comment]
GuPPy supports doric file now. You do not need to convert it to csv by yourself

Can I please see the screenshots of your csv files you created ?

**Comment by zova137** [comment]
Here are the content and files that I tried to create in suitable formatting:
![image](https://user-images.githubusercontent.com/60068522/230999135-9fc8e35d-5f1e-46ef-aabc-c1680e40eec1.png)
![image](https://user-images.githubusercontent.com/60068522/230999087-322f12b5-ea21-46b7-a1bf-81bca7b38ad8.png)
![image](https://user-images.githubusercontent.com/60068522/230999000-73f9c5f7-2db4-4f93-8941-61be1a6dfe2d.png)

**Comment by venus-sherathiya** [comment]
control and signal files should have three columns with column names [timestamps, data, sampling_rate] 

TTL files should have one column with column name [timestamps]

Note : everything in lower case and no typo errors (you have typo error in your files). Also, all the columns should have relevant data (no empty columns)

**Comment by venus-sherathiya** [comment]
It should work without any issues or error if the first few seconds of data is empty

**Comment by zova137** [comment]
I fixed the typo in the column name, but still doesn't work! I will try another doric file in the next week and let you know the result!

**Comment by venus-sherathiya** [comment]
Sure !! if you cannot figure out, please let me know. We can meet on zoom and try to help you out

**Comment by venus-sherathiya** [comment]
Addressed it before !!
