### ISSUE TITLE
Neurophotometrics file - storenames not recognised

### ISSUE THREAD

**Issue by NRD23-cre** [LernerLab/GuPPy#39]
Hello, 

I get this alert everytime I try and get storenames.

Alert !!
No storenames found. There are not any TDT files or csv files to look for storenames.

I am using files directly collected from neurophotometrics, and appear to be formatted the same as the sample data. Any ideas?

**Comment by venus-sherathiya** [comment]
Can I see how your NPM files look like ?
Please send me the screenshot of those files ?
Also, are you selecting the folder in which files are there or the files itself in the input parameters GUI ?

**Comment by venus-sherathiya** [comment]
when you select a folder, how many files do you keep in a folder ?

**Comment by venus-sherathiya** [comment]
Usually I have seen that in NPM data, isosbestic and signal data are in the same file. Why is it different in your case ? 
maybe, that is the issue.

**Comment by NRD23-cre** [comment]
Yes, I have two folders, one at 470 and one at 415, so I will double check how the data is exported and see if that corrects the issue. Thank you

**Comment by NIADFA** [comment]
I was unfortunately not able to correct the issue. Are there any other fixes?

**Comment by venus-sherathiya** [comment]
I see !! Let me look into it next week and I will try to fix it.
If possible, can you please send me any of your sample data at venus.sherathiya@northwestern.edu ?
