### ISSUE TITLE
IndexError: index 7428 is out of bounds for axis 0 with size 7428

### ISSUE THREAD

**Issue by kai-price** [LernerLab/GuPPy#40]
Hello!

I am getting the error message in the subject line when I attempt to extract timestamps and its correction, but I don't know what this error means. I tried adjusting several input parameters and kept getting this error. Thank you!

**Comment by kai-price** [comment]
Hello, yes I just downloaded the most recent version of GuPPy. I am using NPM data.

**Comment by venus-sherathiya** [comment]
I never saw this error when you are working with NPM. Please delete the output folder for the data you were getting this error. And try to re-run the analysis from the start with the most recent version of GuPPy. Please let me know if you still get this error.

**Comment by kai-price** [comment]
I figured out the issue. Thanks!
