### ISSUE TITLE
Step 4 : Extract timestamps  and its correction- data does not show up

### ISSUE THREAD

**Issue by geofftheriverfish** [LernerLab/GuPPy#44]
After running step 3 (read raw data) and then running step 4: Extract timestamps 
and its correction, I do not have any data which appears on the screen. There have been no error messages on terminal. Why is the data not appearing ? 

Many thanks

**Comment by venus-sherathiya** [comment]
What's your data format (like NPM, Doric, TDT or csv) ? Can I see the screenshot of your output folder after running Step 3 and Step 4 ? Also, can I see the screenshot of storeslist.csv file which should be there in your output folder ?
