### ISSUE TITLE
Missing sampling rate with manually made ttl files

### ISSUE THREAD

**Issue by djm18** [LernerLab/GuPPy#47]
Hi, I have been using GuPPy for neurophotometrics data and it works great when I'm only working with one or two behaviors that can be represented as booleans. However when I need to work with more than two behaviors and I manually make multiple ttl files representing each behavior using the single timestamps column, suddenly my generated chev and chod files lose the sampling_rate column and the whole thing stops working. I notice someone on the gitter page had the exact same issue as me so maybe you already know what I'm talking about. My goal is to be able to use GuPPy for neurophotometrics with multiple different behaviors so I hope you can please help with this.

**Comment by venus-sherathiya** [comment]
are you using the most recent version of GuPPy ?
also, who raised a similar issue in gitter chat room ? May I please know the ID so that it is easy for me to search the thread ?

**Comment by djm18** [comment]
I am using the most recent version of GuPPy as of 06/09/2023.
The issue was originally raised by Tonecs, below is a link his messages in the chat room https://matrix.to/#/!yTGCvVoqQboYukoeoX:gitter.im/$_hDPjGiwIXJf1X2J1U7qJDDqDGvTQV6kGOD96D05RdQ?via=gitter.im&via=matrix.org

**Comment by djm18** [comment]
Issue getting addressed in gitter chat room
