### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LUTaha** [LernerLab/GuPPy#48]
Hi,

I get this error when I try to run group analysis through guppy. Any ideas?

data_csv
event_csv
Launching server at http://localhost:5056
['20230623_00602_06557_signal', '20230623_00602_06557_control', '20230623_00602_06557_timestamp']
[['20230623_00602_06557_signal' '20230623_00602_06557_control'
  '20230623_00602_06557_timestamp']
 ['signal_06557' 'control_06557' 'Injection1']]
Input Parameters File Saved.
Computing PSTH, Peak and Area for each event...
Average for group :  True
Averaging group of data...
Traceback (most recent call last):
  File "computePsth.py", line 682, in <module>
    psthForEachStorename(json.loads(sys.argv[1]))
  File "computePsth.py", line 636, in psthForEachStorename
    averageForGroup(storesListPath, storesList[1,k], inputParameters)
  File "computePsth.py", line 489, in averageForGroup
    new_path[idx].append(path[i])
IndexError: list index out of range
Finding transients in z-score data and calculating frequency and amplitude....
Combining results for frequency and amplitude of transients in z-score data...
Traceback (most recent call last):
  File "findTransientsFreqAndAmp.py", line 326, in <module>
    executeFindFreqAndAmp(json.loads(sys.argv[1]))
  File "findTransientsFreqAndAmp.py", line 294, in executeFindFreqAndAmp
    averageForGroup(storesListPath, inputParameters)
  File "findTransientsFreqAndAmp.py", line 245, in averageForGroup
    new_path[idx].append(path[i])
IndexError: list index out of range

**Comment by venus-sherathiya** [comment]
May I please see the screenshots of all the storeslist.csv file from the output folder which you are selecting for group analysis ? 

Thank you !!

**Comment by LUTaha** [comment]
![MicrosoftTeams-image (12)](https://github.com/LernerLab/GuPPy/assets/115993502/a05b4b1f-9ce5-420f-8c06-2d3183f0b825)

Does this help?

**Comment by venus-sherathiya** [comment]
I am so sorry !!
I am having a hard time following the storeslist.csv file.
I want to look at the storeslist.csv files which gets saved in the data folder when you run individual analysis. So, if you are selecting 4 folders for group analysis. I wanna see all 4 storeslist files which are inside those folders.

**Comment by alanpkania** [comment]
Hello,
having very similar issue trying to average across files:

Input Parameters File Saved.
Read progress bar increment values function started...
Computing PSTH, Peak and Area for each event...
Average for group :  True
Averaging group of data...
Traceback (most recent call last):
  File "C:\Users\alank\GuPPy-main\GuPPy\computePsth.py", line 772, in <module>
    raise e
  File "C:\Users\alank\GuPPy-main\GuPPy\computePsth.py", line 763, in <module>
    inputParameters = psthForEachStorename(json.loads(sys.argv[1]))
  File "C:\Users\alank\GuPPy-main\GuPPy\computePsth.py", line 700, in psthForEachStorename
    averageForGroup(storesListPath, storesList[1,k], inputParameters)
  File "C:\Users\alank\GuPPy-main\GuPPy\computePsth.py", line 538, in averageForGroup
    new_path[idx].append(path[i])
IndexError: list index out of range

Attaching my storelist files.

[storesList (2).csv](https://github.com/LernerLab/GuPPy/files/13976858/storesList.2.csv)
[storesList (3).csv](https://github.com/LernerLab/GuPPy/files/13976859/storesList.3.csv)
[storesList (4).csv](https://github.com/LernerLab/GuPPy/files/13976860/storesList.4.csv)
[storesList (5).csv](https://github.com/LernerLab/GuPPy/files/13976861/storesList.5.csv)
[storesList (6).csv](https://github.com/LernerLab/GuPPy/files/13976862/storesList.6.csv)
[storesList (7).csv](https://github.com/LernerLab/GuPPy/files/13976863/storesList.7.csv)
[storesList (8).csv](https://github.com/LernerLab/GuPPy/files/13976864/storesList.8.csv)
[storesList (9).csv](https://github.com/LernerLab/GuPPy/files/13976865/storesList.9.csv)
[storesList (10).csv](https://github.com/LernerLab/GuPPy/files/13976867/storesList.10.csv)
[storesList (11).csv](https://github.com/LernerLab/GuPPy/files/13976868/storesList.11.csv)
[storesList (12).csv](https://github.com/LernerLab/GuPPy/files/13976869/storesList.12.csv)
[storesList (13).csv](https://github.com/LernerLab/GuPPy/files/13976870/storesList.13.csv)
[storesList (14).csv](https://github.com/LernerLab/GuPPy/files/13976871/storesList.14.csv)
[storesList (15).csv](https://github.com/LernerLab/GuPPy/files/13976872/storesList.15.csv)
[storesList.csv](https://github.com/LernerLab/GuPPy/files/13976873/storesList.csv)

I did not have isosbestic control in my experiment.

Best regards,
Alan

**Comment by venus-sherathiya** [comment]
Let me explain how group analysis works :

Let's say, you have two group : X and Y

The storeslist files for all the data corresponding to group X should have signal_X and control_X

The storeslist files for all the data corresponding to group Y should have signal_Y and control_Y

So, basically X and Y work as identifiers. When I look into your storeslist files, I could not find any common identifiers which can be used for group analysis.

I hope this helps. If not, please let me know

**Comment by venus-sherathiya** [comment]
Closing issue because no further questions asked !!
