### ISSUE TITLE
Stuck on Timestamps

### ISSUE THREAD

**Issue by JJ-JW** [LernerLab/GuPPy#49]
Using the sample Clean TDT data and get the following sequence in the terminal window followed by the error that hangs the program-

### Trying to read tsq file....
Data from tsq file fetched....
Reading data for event Dv1A ...
Reading data for event Dv3B ...
Data for event Dv1A fetched and stored.
Data for event Dv3B fetched and stored.
Reading data for event Dv2A ...
Reading data for event Dv4B ...
Data for event Dv4B fetched and stored.
Reading data for event LNRW ...
Data for event LNRW fetched and stored.
Reading data for event LNnR ...
Data for event LNnR fetched and stored.
Reading data for event PrtN ...
Data for event PrtN fetched and stored.
Reading data for event PrtR ...
Data for event PrtR fetched and stored.
Reading data for event RNPS ...
Data for event Dv2A fetched and stored.
Data for event RNPS fetched and stored.
Time taken = 8.60388
Raw data fetched and saved.
Extracting signal data and event timestamps...
Remove Artifacts :  False
Combine Data :  False
Isosbestic Control Channel :  True
Correcting timestamps by getting rid of the first 1 seconds and convert timestamps to seconds...
Timestamps corrected and converted to seconds.
Applying correction of timestamps to the data and event timestamps...
Timestamps corrections applied to the data and event timestamps.
Applying correction of timestamps to the data and event timestamps...
Timestamps corrections applied to the data and event timestamps.
Applying correction of timestamps to the data and event timestamps...
Timestamps corrections applied to the data and event timestamps.
Applying correction of timestamps to the data and event timestamps...
Timestamps corrections applied to the data and event timestamps.
Applying correction of timestamps to the data and event timestamps...
Timestamps corrections applied to the data and event timestamps.
Applying correction of timestamps to the data and event timestamps...
Timestamps corrections applied to the data and event timestamps.
Applying correction of timestamps to the data and event timestamps...
Timestamps corrections applied to the data and event timestamps.
Applying correction of timestamps to the data and event timestamps...
Timestamps corrections applied to the data and event timestamps.
Applying correction of timestamps to the data and event timestamps...
Timestamps corrections applied to the data and event timestamps.
Computing z-score for each of the data...
Remove Artifacts :  False
Remove Artifacts :  False
z-score for the data computed.
invalid command name "140348261455104stayOnTop"
    while executing
"140348261455104stayOnTop"
    ("after" script)

**Comment by jwenzel-0727** [comment]
I'm having the same issue - any progress?

**Comment by JJ-JW** [comment]
No reply yet. Have tried with demo data and with our TDT data-still hangs up at the timestamps with the same error. 

Might try reloading the code in case it was updated since the last time I downloaded it.

What have you tried?

**Comment by jwenzel-0727** [comment]
Just starting to troubleshoot. I'm getting this error with my TDT data. I just loaded the code last week. Let me know if it works!

**Comment by jwenzel-0727** [comment]
Oh, welp, I think it's working now. You have to close the pop-up window of your data for it to continue on.

**Comment by JJ-JW** [comment]
Yes, that seems to work. Trying it out on actual data from our rig

**Comment by venus-sherathiya** [comment]
Sorry for late response !! Is everything working now ? If possible, whenever you have an issue in the future, please post it on Gitter chat room because it sends me a notification when a message is posted. It helps me reply quick.

**Comment by JJ-JW** [comment]
Hi Venus,

Yes, was a simple matter of closing the graph windows before going  to the Timestamps.

John


John J. Woodward, PhD
Professor; Dept. of Neuroscience and Dept. of Psychiatry
Medical University of South Carolina
Office STB627B
843-792-5225 (office)
Lab website: http://people.musc.edu/~woodward/

*********************************************
Addresses
for US Postal Service deliveries
Dept of Neuroscience
MSC 510
Charleston, SC 29425

for Courier Services (UPS, FedEx)
30 Courtenay Drive
STB627B
Charleston, SC 29425


From: Venus Sherathiya ***@***.***>
Date: Monday, September 11, 2023 at 2:03 PM
To: LernerLab/GuPPy ***@***.***>
Cc: Woodward, John ***@***.***>, Author ***@***.***>
Subject: Re: [LernerLab/GuPPy] Stuck on Timestamps (Issue #49)

CAUTION: External

Sorry for late response !! Is everything working now ? If possible, whenever you have an issue in the future, please post it on Gitter chat room because it sends me a notification when a message is posted. It helps me reply quick.

**Comment by venus-sherathiya** [comment]
closing the issue now !! Please feel free to reach out for any issue in the future. I will be try to be quicker in my response
