### ISSUE TITLE
Issues with running GuPPy

### ISSUE THREAD

**Issue by h1408** [LernerLab/GuPPy#5]
Hi! I am trying to run Guppy on some of my own data acquired from TDT. I do not have storenames of behaviors, since I handscored the time stamps of different behaviors of interest. Do I need to import this somehow into the storenames GUI?
Thank you for your help!

**Comment by venus-sherathiya** [comment]
you can create a csv file of your handscored timestamps following the structure as shown in the file [SampleData_TTL.csv](https://northwestern.app.box.com/s/pmzpqey540gkftka669frax84ofk5f4h/folder/142667726166).
Copy created TTL csv files in the same folder where your TDT data is present and run the analysis.
In this way, you will have storenames from TDT and you will also see TTL filenames as storenames in the Storenames GUI.

**Comment by h1408** [comment]
Hi! I tried to do this by adding in the onset times of my handscored data using the same format as the SampleData_TTL.csv file. It has a heading in lowercase of 'timestamps' and underneath is a few rows of the timestamps. However, I notice the following error in my my terminal when I try to open the storenames GUI. I'm not sure why this is happening, since the sample csv file only has one column and my file is in the same format. I'm not even sure how I would get the sampling rate/data to fill in two other potential columns. Do you have any insight into this? 

` in import_np_csv
    raise Exception("\033[1m"+"Column names should be timestamps, data and sampling_rate (all lower-cases)"+"\033[0m")
Exception: Column names should be timestamps, data and sampling_rate (all lower-cases)`

I also had a couple other questions as I am trying to work through my data:
- Can the timestamps include onset and offset? In other words, when I import my handscored events can I include the onset and offset time of a behavior so that I could take a look at the trace during the whole epoch as well do a PSTH based on the onset time? 
- I would like to be able to define by F for deltaF/F based the F from the first ~2 minutes of the trace instead of a moving average. To clarify, in order to do this, should I set the "Window for Moving Average filter (int)" to 0 and change "z-score computation method" to "baseline z score" and note the times that I want to use to calculate in this section? 
- 
Thank you so much for your help!

**Comment by venus-sherathiya** [comment]
First things first, lets solve the error first 
can I please see the screenshot of the folder where your data is present and also the screenshot of the csv file which you are using for event TTLs ?

**Comment by h1408** [comment]
Yes, attached are screenshots of both of these
![Screen Shot 2021-12-02 at 3 33 21 PM](https://user-images.githubusercontent.com/80368001/144519540-928da34e-f35c-4e5d-a907-670556e46a4f.png)
![Screen Shot 2021-12-02 at 3 33 47 PM](https://user-images.githubusercontent.com/80368001/144519583-4fc0d712-191f-4b06-80fb-9c4ff4b3c601.png)

**Comment by venus-sherathiya** [comment]
there is a file named 'cottonballonset.csv' in the same folder. please don't keep that file in there.
GuPPy tries to find all the 'csv' file present in the folder and checks the structure of the file. That file does not have that specific structure so it is throwing an error. If you run the analysis by removing that file, the analysis will run properly. Please let me know if you come across any problems.

**Comment by h1408** [comment]
I tried doing that and it worked! Thank you! 
Would you have any insights on the other questions?

**Comment by venus-sherathiya** [comment]
I didn't get your second question. I didn't understand what you want to achieve. Can you please elaborate on it ?

For the first question, does the time difference between onset and offset remains the same in the whole recording session ?

**Comment by venus-sherathiya** [comment]
done !!
