### ISSUE TITLE
Stuck on read raw data

### ISSUE THREAD

**Issue by NadineKGut** [LernerLab/GuPPy#51]
SOLVED (messed  up in open storenames GUI; understood that the saving at the bottom was only if I want to make changes to the storenames) - Hi, as many have commented before, this is a fantastic tool and such a treat for someone with little (no) coding experience. Thank you! But unfortunately, for the same reason I cannot troubleshoot (yet). I do not get any data displayed when hitting "extract timestamps and its correction" and realised that after "read raw data" there is no output file in my source folder. Can you please advise how I can fix that?

**Comment by venus-sherathiya** [comment]
May I see your storeslist.csv file ?

**Comment by venus-sherathiya** [comment]
No further activity -- so closing this issue
