### ISSUE TITLE
can't open file 'readTevTsq.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by kilomaniz** [LernerLab/GuPPy#53]
Hello,  I am a PhD student and I am trying to learn by myself to use fiber photometry on a tdt set up. My question may seem stupid but I am trying to analyze my data and when I am running the "read raw data" procedure, the following message is displayed in my terminal : "can't open file 'readTevTsq.py': [Errno 2] No such file or directory" . The python file is however in the folder "guppy-main". Can someone help me solve this? Thank you

**Comment by a-leach** [comment]
Hi @kilomaniz, after updating GuPPy, I am running into the same issue with my data. I was not receiving this error prior to updating. I'm not sure how to fix it, but just wanted to let you know that you're not the only one experiencing that issue.

**Comment by venus-sherathiya** [comment]
after the update, follow the steps on [Github Wiki page](https://github.com/LernerLab/GuPPy/wiki). As you have already updated the condo environment, skip step d. Please let me know if it does not work.

**Comment by kilomaniz** [comment]
Thank you for your answers. I uninstalled and reinstalled Guppy Main and now it works.
