### ISSUE TITLE
Wrong Timestamps during Visualization-step

### ISSUE THREAD

**Issue by FlobbyDobby** [LernerLab/GuPPy#54]
Hi,

I have recently started using GuPPy and ran into a problem during the visualization-step,

It appears that the used timestamps during this step are consistantly 1 second less than what in inputed in the TTL-file (see image),

Why is this?

![Screenshot 2023-09-28 150342](https://github.com/LernerLab/GuPPy/assets/115487862/4cb5686b-a1cc-43ed-ae64-92f5ec1152e4)

**Comment by venus-sherathiya** [comment]
In the Input Parameters GUI, there is a parameter called "Eliminate first few seconds". This parameter eliminates the first x seconds from the data. Default is 1 second.
