### ISSUE TITLE
Issues with Parameters GUI using NeuroPhotometrics

### ISSUE THREAD

**Issue by R2roRiver** [LernerLab/GuPPy#55]
Hi! I am a Postbac using Guppy to analyze Neurophotometric csv files. I have been able to use it successfully for some of my data, but for others I encounter the same error in the Parameters GUI Step. I notice that the Guppy produced files seems to be incomplete and results in the error seen in the command console. I am not sure where the issue lies. Here is also a screenshot of my csv files.
<img width="194" alt="Screenshot 2023-10-02 at 11 22 56 AM" src="https://github.com/LernerLab/GuPPy/assets/146751378/f2dc48e7-3027-46fa-bc92-097e7cc0a783">

![Screenshot 2023-10-02 111631](https://github.com/LernerLab/GuPPy/assets/146751378/1440e549-6d4c-42ad-9691-0b66ce2176b8)
![Screenshot 2023-10-02 111724](https://github.com/LernerLab/GuP
Py/assets/146751378/90c139e5-07d4-441f-9e67-009d21e12da8)
<img width="634" alt="Screenshot 2023-10-02 at 11 22 19 AM" src="https://github.com/LernerLab/GuPPy/assets/146751378/aa0b399b-287b-4073-ac0d-ecf307eed206">

**Comment by venus-sherathiya** [comment]
I did not get it. At what step in the analysis process, are you getting this error ?
And can you please full screen your terminal window and take a full screenshot of your error ?

**Comment by R2roRiver** [comment]
Sorry for the delay! I meant the "Open Visualization Part". After putting in my files I can go through the Open Storenames step up until the Extract Timestamps steps without issue. Despite this, I cannot proceed with Open Visualization step. Here is the terminal with error code in the bottom.
![Screenshot 2023-10-05 160333](https://github.com/LernerLab/GuPPy/assets/146751378/d937748a-fd16-4ba9-aa03-c02dd4400ec8)

**Comment by venus-sherathiya** [comment]
I think you got this error because you probably got an error in one of the earlier steps. Delete the output folder. Re-run the analysis and please look at the terminal window at each step. Please let me know what you find
