### ISSUE TITLE
Wanting to not use isosbestic channel that's in my data

### ISSUE THREAD

**Issue by h1408** [LernerLab/GuPPy#57]
Hi, I am trying to use guppy to get control channels as if there were no isosbestic channel (even though there is data from a 405 channel from my TDT recording), and I do set that parameter to 'False' when saving input parameters, however I do not see output in the terminal that it is creating a control channel. Rather, I see that it says that data is fetched and saved for the 405 channel from the Tev/Tsq file. Is there anything else I need to do in order to make sure I can get a simulated control channel from guppy and not use the 405 from my TDT data? Thank you in advance for your help!

**Comment by venus-sherathiya** [comment]
Try to complete Extract timestamps and its correction step and see if it gets completed without any errors

**Comment by venus-sherathiya** [comment]
Also, please make sure not to use 405 storename while saving storeslist file in Storenames GUI

**Comment by h1408** [comment]
Hi thanks so much! I did that and I think it is fixed now, but what is the difference between 'control_BNST.hdf5' output and the 'cntrl0.hdf5' output? Which of those is used as the F for the dff calculation?

**Comment by venus-sherathiya** [comment]
To answer your question, can you please delete the output folder and run the analysis again. After that, please send me the screenshot of the output folder and storeslist.csv file ?

**Comment by h1408** [comment]
Hi, thanks! Yes I ran it on a new recording. Here are the screenshots: 
![Screenshot 2023-10-26 at 2 08 37 PM](https://github.com/LernerLab/GuPPy/assets/80368001/03f0a8b6-13bd-49af-ae04-187bb7934286)

![Screenshot 2023-10-26 at 2 08 51 PM](https://github.com/LernerLab/GuPPy/assets/80368001/83259c65-1f0a-450e-bdec-172a5c0aefbe)

**Comment by venus-sherathiya** [comment]
control_BNST will be used for dff calculation

**Comment by h1408** [comment]
Okay and is  465A or the signal_BNST traces used as the signal in for dff? Also is cntrl0 is used for anything? Because when I plot it seems to follow the signal (see below). I appreciate your help with this! 

![Screenshot 2023-10-26 at 2 14 51 PM](https://github.com/LernerLab/GuPPy/assets/80368001/09d1e57b-8222-4c55-a714-f975e58131cf)

**Comment by venus-sherathiya** [comment]
cntrl0 is similar to 465A. cntrl0 is used to compute control_BNST. control_BNST and signal_BNST are used for dff calculation.

**Comment by venus-sherathiya** [comment]
Hello, Should I close this issue ?

**Comment by h1408** [comment]
Hi, yes thank you so much for your help!

**Comment by venus-sherathiya** [comment]
issue resolved !!
