### ISSUE TITLE
Excel File Output

### ISSUE THREAD

**Issue by nathanyalross** [LernerLab/GuPPy#60]
I am trying to visualize this data outside of GuPPy, and I have a timepoint of injection that I did not label with a ttl. I was wondering if there was a way to get the z-score for the data in a csv as an output so that I can use another program to visualize this data, thanks!

**Comment by venus-sherathiya** [comment]
I didn't get your question completely. What do you wanna visualize and which program do you wanna use for visualization ?

**Comment by nathanyalross** [comment]
Sorry, guess I'm not exactly sure how to word it. I would like to visualize the data in prism, and to do this I'm imagining that I would need a csv with z-score values for every sample. I injected CNO and I have the time of that injection written down, and I would like to use that information with prism visualization to mark the time of injection relative to the trace. Unless if there is some way that I can mark that timestamp in GuPPy, by manually inputing the timestamp. I apologize if I'm not making sense, I'm still new to this, but thanks for your help!

**Comment by venus-sherathiya** [comment]
I get what you mean. Can make a csv of your injection timestamps and run the analysis in the GuPPy ? The csv file for the timestamps should look like [this](https://drive.google.com/drive/folders/1wODHMpoStIg2ZHmlH5zJhakYDCicmc8A) In this way, you will be able to see visualize your data in GuPPy. In the visualization GUI, you have an option to save the plots in PNG or SVG format.

**Comment by nathanyalross** [comment]
Awesome, I can make a csv of those timestamps. How do I pass this csv into guppy?

**Comment by venus-sherathiya** [comment]
Put that csv file in the same folder where you fiber photometry raw data is located. Your fiber photometry data is collected using which system (TDT, Doric or NPM? ?

**Comment by nathanyalross** [comment]
TDT

**Comment by venus-sherathiya** [comment]
Okay. Put the csv inside the folder where your TDT files are present.

**Comment by venus-sherathiya** [comment]
Did it work for you ? If yes, can I close this issue ?

**Comment by nathanyalross** [comment]
Oh yes, this worked! Thank you for the assistance

**Comment by venus-sherathiya** [comment]
It is resolved !!
