### ISSUE TITLE
Non Chronological Sorting of Trials in Heatmap

### ISSUE THREAD

**Issue by rkast1** [LernerLab/GuPPy#62]
Is there some way to visualize a heatmap with trials sorted based on some behavioral variable I've measured that is neither chronological nor discrete with a small number of categories (which would be easily solvable by generating separate eventTTL files for each of the few categories)? When I try to provide an eventsTTL file that I have presorted, the visualization gui only ends up displaying the trials that maintain their chronological ordering after the sorting. So, I go from having say 60 trials that are sorted by variable x in my eventsttl.csv to having just 5 events in the heatmap, which happen to be those that are in the same chronological order before and after sorting by my variable of interest. Thanks!

**Comment by venus-sherathiya** [comment]
Sorry for the late response, I was on a vacation. In this issue, I can help you best if we meet on a zoom . Please send me your availability at Venus.sherathiya@northwestern.edu.

**Comment by venus-sherathiya** [comment]
Closing issue because no further activity on the issue
