### ISSUE TITLE
PSTH Error

### ISSUE THREAD

**Issue by likpole** [LernerLab/GuPPy#63]
Hello!
I am currently attempting to analyze some data, but am receiving an error when running the PSTH computation. I am unsure of what the error means or how to solve it. Could you please help! I have attached the error image and my PSTH parameters that I have set. 
Thank you for this amazing program!

![image](https://github.com/LernerLab/GuPPy/assets/153773910/54d63ad3-3f51-42f1-a94b-675ec883fdde)
![image](https://github.com/LernerLab/GuPPy/assets/153773910/66a857b3-02cd-4a35-af1b-d96d52b9629b)

**Comment by venus-sherathiya** [comment]
I think there should be problem with your sampling rate. Your data file may not represent the correct sampling rate. What system are you using for data recording (TDT, NPM, Doric or something else) ?

**Comment by likpole** [comment]
I am using RWD. The sampling rate is set as 30 fps. I have also attached a screenshot of my data if needed. 
![image](https://github.com/LernerLab/GuPPy/assets/153773910/15e6f1a4-4e0a-4cd0-ac17-f50d862ef7c4)

**Comment by venus-sherathiya** [comment]
if you look at your timestamps, the sampling rate turns out to be 15. please double check on it.

**Comment by likpole** [comment]
Thank you so much! I was able to get it to work. I was wondering if you had any suggestions to make the data filter better. I am currently getting z-score data that does not look very linear and I was told that the z-score should be straight. 

![image](https://github.com/LernerLab/GuPPy/assets/153773910/fdc8482d-61e0-4bcb-981d-e6bce7b9d7b7)

**Comment by venus-sherathiya** [comment]
How does the plots in Extract timestamps and it's correction looks like ?

**Comment by likpole** [comment]
Here is the extract timestamps and correction graph!
![image](https://github.com/LernerLab/GuPPy/assets/153773910/28b1ab5b-c4da-48b5-a81c-908bb346797c)

**Comment by venus-sherathiya** [comment]
please do artifact removal for this data and I think it will look good

**Comment by likpole** [comment]
Thank you so much for all your help! I really appreciate everything and answering all my questions! This is a great program, so thank you very much!
