### ISSUE TITLE
Error during artifact removal 

### ISSUE THREAD

**Issue by PochapskiJose** [LernerLab/GuPPy#64]
Hi, 
I'm using Guppy with csv. files and I could run individual and group analyses and also visualize them on GUI. However, with my new files I needed to remove some artifacts (as shown on fig 1). 
<img width="633" alt="Screenshot 0" src="https://github.com/LernerLab/GuPPy/assets/151056137/c4627553-a6ed-4f48-82ca-ff476e27980e">
 
I followed all the steps in the tutorial (and also from the video tutorial), but I could never visualize the data on GUI. I tried a lot of different combinations (changing parameters, order of the steps, folders, and different datasets, etc) but none of it worked. 
I was re-watching the video tutorial an I noted something that was there compared to the information that I was seeing on my terminal windows. As shown in fig 2, when I draw the lines to select the data without the artifact I have the X coordinate showed there, but my Y coordinate is always 0 there (on the tutorial video there was a specific number for the Y coordinate). I'm not sure if this is the problem, but it's something different that I noted. 

<img width="570" alt="Screenshot 1" src="https://github.com/LernerLab/GuPPy/assets/151056137/f2ace2b0-ee0c-476e-9e60-fa89a606ca41">

 But besides it I could save the coordinates and also generate the updated data without the artifact. 

<img width="572" alt="Screenshot 2" src="https://github.com/LernerLab/GuPPy/assets/151056137/84819f13-c91f-404e-a5a4-6358a37b2ebc">
<img width="1379" alt="Screenshot 3" src="https://github.com/LernerLab/GuPPy/assets/151056137/6d4925e8-19c3-4a31-b8ed-5bb1b29292b7">

<img width="1381" alt="Screenshot 4" src="https://github.com/LernerLab/GuPPy/assets/151056137/6111fc17-4f6e-478e-98fb-aabe7fa7fdf7">

I could also move forward and run the PSTH compilation step and generate the figure (as in the figure bellow).

<img width="1388" alt="Screenshot 5" src="https://github.com/LernerLab/GuPPy/assets/151056137/8492880f-c009-4588-9557-e72b0e88d688">

But I noted also an error message there regarding TTLs visualization (but the zscore graph after the PSHT is still generated). Its weird because if I run this file without the artifact removal for individual analyses this error message don't appear on the terminal and I can open the data on GUI.

<img width="568" alt="Screenshot 6" src="https://github.com/LernerLab/GuPPy/assets/151056137/6ebf13b6-8177-4a02-9c7d-790f877b2450">

Then when I move to the final step of the analysis to see the data on GUI, there is this other error message:

<img width="570" alt="Screenshot 7" src="https://github.com/LernerLab/GuPPy/assets/151056137/4ae4ad63-3538-43e5-bcc8-49d82604019e">

Do you have some idea what could be the problem that is not allowing me to visualize the data on GUI after the artifact removal?

**Comment by venus-sherathiya** [comment]
Sorry for the late response, I was on a vacation. I am not sure what are you doing wrong. can we please meet on a zoom call ? Please send me your availability at Venus.sherathiya@northwestern.edu.

**Comment by venus-sherathiya** [comment]
Addressed the issue on a zoom call and small changes to the code.
