### ISSUE TITLE
Issue with launching Step 1

### ISSUE THREAD

**Issue by h1408** [LernerLab/GuPPy#65]
Hi, I had been using a version of GuPPY where the code I had downloaded was downloaded on 7/7/2023. I was having some trouble with reading the raw data in Step 3 (similar to closed issue #53) so I thought I needed to update something.
I read on the README document that if I am a current user I could download the new code from the github and update it, which I did do. I deleted the GuPPY folder I previously had, downloaded the new one, and then I ran the `conda update -n guppy --file filename` command for the mac specific txt file. There were a lot of updates that were made and new packages were added. 
Then I closed out of terminal completely and started GuPPY from scratch as listed in the Wiki, however, when I ran `panel serve --show GuPPy/savingInputParameters.ipynb`, I got this popup I hadn't seen before which asked me to select the folder path for GuPPY's input parameters GUI. I selected the folder where the "savingInputParameters.ipynb" file was. Then the GUI opened but it doesn't show the files of my computer, just the GUPPY code folder and I cannot navigate to other places where my recordings are stored. 
Is there something else I need to do to get it to work again? Do I need to update the conda environment at all? I appreciate your help with this !
![Screenshot 2023-12-19 at 5 08 54 PM](https://github.com/LernerLab/GuPPy/assets/80368001/3864dfac-fefa-477a-a98c-0709cc577858)

**Comment by h1408** [comment]
I also wanted to add in what I see in the terminal:
`panel serve --show GuPPy/savingInputParameters.ipynb

2023-12-20 11:35:00,593 Starting Bokeh server version 2.4.3 (running on Tornado 6.2)
2023-12-20 11:35:00,594 User authentication hooks NOT provided (default user enabled)
2023-12-20 11:35:00,599 Bokeh app running at: http://localhost:5006/savingInputParameters
`

**Comment by venus-sherathiya** [comment]
My bad, I am sorry !! Use the update the code from Github and it will work for you.

**Comment by venus-sherathiya** [comment]
Also, if it works, please close this issue !!

**Comment by h1408** [comment]
I tried that and now I get a pop up that asks me to select where my data is stored and when I select the folder the GUI opens and I am able to proceed! 
Thanks so much for your help!
