### ISSUE TITLE
csv file 

### ISSUE THREAD

**Issue by samjadot** [LernerLab/GuPPy#66]
Good morning,
The CSV file containing the timestamps of the events I want to analyse is not readable by the program. Nothing happens when I press "open storename GUI" but when this csv file is not there it works. Here is what is written in the terminals :raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['Time(s)'] not found in axis".
Thanks for your help 
[FU.csv](https://github.com/LernerLab/GuPPy/files/14062275/FU.csv)
here the file CSV that i use.

**Comment by venus-sherathiya** [comment]
The csv file is not according to the format which GuPPy wants. If your csv file has TTL timestamps, it should look like the sample file I attached here. There should be one column with column name as "timestamps" and this column will have all the TTL timestamps in it.
[Sample_TTL.csv](https://github.com/LernerLab/GuPPy/files/14142990/Sample_TTL.csv)

**Comment by samjadot** [comment]
i thanks a lot it works but I'm blocked again  after I've done step 2: Open Storenames GUI
and save storenames, I tried to do step 3 but I'm stuck again here is what is displayed on the terminal :IndexError: list index out of range
['405A', '465A', 'Cam1', 'FU']
Thank you very much

**Comment by samjadot** [comment]
here is the code 
![Capture d’écran 2024-02-06 à 11 10 14](https://github.com/LernerLab/GuPPy/assets/157792111/d83a353c-cb25-4195-a1b3-9afca5e90f58)

**Comment by venus-sherathiya** [comment]
Can I please see the screenshot of your raw data folder ?

**Comment by venus-sherathiya** [comment]
I want to see the folder screenshot where your raw data is present. Does it have '.tev' file in it ? Also, when you open the store names GUI in step 2, please follow the instructions which are written on the left. If you do not follow it, it will throw an error.

**Comment by samjadot** [comment]
here is 
thanks a lot.
![Uploading Capture d’écran 2024-02-08 à 08.59.30.png…]()

**Comment by samjadot** [comment]
It is ok it'is work now. Thank you for your help.:)

**Comment by venus-sherathiya** [comment]
Awesome !! Issue resolved
