### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by PedrosoJAB** [LernerLab/GuPPy#67]
Hi,
I was trying open the doric file  of my Fiber photometry recording, but I can't open my file on GuPPy. When I try to run  it returns a "permission denied" error in the conda prompt.   I don't exactly know what it means nether how to handle it. So, I wonder if someone could help me with that. Thanks.

**Comment by venus-sherathiya** [comment]
Where are your files located in your machine ? Is it somewhere where you cannot access the file ?

**Comment by PedrosoJAB** [comment]
No, I stored them in a folder on my desktop.

**Comment by venus-sherathiya** [comment]
Is your desktop folder connected to online drive like OneDrive, iCloud etc ?

**Comment by PedrosoJAB** [comment]
Now it worked. Thanks.
