### ISSUE TITLE
Exception: Error in naming convention of files or Error in storesList file Read progress bar increment values stopped.

### ISSUE THREAD

**Issue by Ninoharaa** [LernerLab/GuPPy#68]
Hello, I'm trying to run analysis from sample data provided on the drive (.doric ones) and I'm stuck on the "extract timestamps and it's correction" step. I loaded the Sample_Data_doric in GuPPy and the storenames were proposed automatically according to columns names. But then when I want to extract the timestamps and corrections it says "Error in naming convention of files or Error in storesList file Read progress bar increment values stopped"... I don't know what to change since the data are provided this way from the drive.

Thanks for help.

**Comment by venus-sherathiya** [comment]
Can I see the storeslist.csv file which got created in the output folder ? Also, please make sure you follow the naming convention properly when storing the storenames in step 2. There are instructions on the left side when you open the Storenames GUI in step 2.

**Comment by venus-sherathiya** [comment]
issue resolved because no further activity
