### ISSUE TITLE
JSONDecodeError after Read Raw Data

### ISSUE THREAD

**Issue by K95R** [LernerLab/GuPPy#69]
Hello! Thank you very much for this tool! I have very little programming experience and I get an error message after clicking on Read Raw Data. The error message is: JSONDecodeError: Expecting value: line 1 column 1 (char 0). Do you have any suggestions how I can solve this problem? 
Thank you!

**Comment by cnikjou** [comment]
I'm also having the same issue. Any help would be greatly appreciated!

**Comment by venus-sherathiya** [comment]
Can you please send me the screenshot of the full error ?

**Comment by cnikjou** [comment]
Below is a screenshot. I'm new to the software, and am using the neurophotometrics data provided in the google drive (SammpleData - 1442 folder)

<img width="1200" alt="JSONDecodeError" src="https://github.com/LernerLab/GuPPy/assets/158687122/1cf73c78-8092-4a4a-a00b-49628857e21f">

**Comment by venus-sherathiya** [comment]
Are you using the following command to launch GuPPy ?
`panel serve --show GuPPy/savingInputParameters.ipynb`

**Comment by cnikjou** [comment]
Yes, I use that exact command, which is the one listed in the GitHub instructions.

**Comment by venus-sherathiya** [comment]
and you are using the updated version of GuPPy, right ?

**Comment by cnikjou** [comment]
Yup, I am using GuPPy-v1.2.0

I will try removing the environment and reinstalling to see if that changes anything

**Comment by venus-sherathiya** [comment]
Before you do that, please try to download the code again from Github and see what happens

**Comment by cnikjou** [comment]
I was in the process of removing the environment...my apologies.

But, now when I run it, I get a new error. Maybe I am commanding to the wrong folder/file?

<img width="1200" alt="image" src="https://github.com/LernerLab/GuPPy/assets/158687122/096ca23c-b5b7-4c34-89af-260f5d9a41dc">

**Comment by venus-sherathiya** [comment]
please fetch the code from the main branch and try again !!

**Comment by cnikjou** [comment]
I am still getting the same error. Could it be the command directory I refer to?

I had trouble with the initial line in the instructions - 'cd path_to_GuPPy_folder' 

So I have just been using 'cd Guppy-v1.2.0', which is stored on my local desktop.

<img width="856" alt="image" src="https://github.com/LernerLab/GuPPy/assets/158687122/26137d4f-efe6-441b-8a56-e8253d8ee139">

**Comment by venus-sherathiya** [comment]
Let's do one thing. We can meet on zoom and I will try to help you out. Please send me an email at venus.sherathiya@northwestern.edu with your availability this week.

**Comment by K95R** [comment]
Hi, I just read all the messages you posted here and I really appreciate you replying to me. I have the same error as cnikjou, but I will attach my error message here anyway. I'm working with the latest version of GuPPy, but as you suggested, I'll download the code again today and see what happens. I would still like to have a Zoom meeting with you to discuss this issue. I will email you soon. 
![ERROR_JSONDecodeERROR](https://github.com/LernerLab/GuPPy/assets/73154635/36c4ed8d-72b1-409a-b666-3acf63a61e3d)

**Comment by venus-sherathiya** [comment]
Issed resolved on zoom call !!
