### ISSUE TITLE
Analyze data on C drive rather than user folder?

### ISSUE THREAD

**Issue by alexritger** [LernerLab/GuPPy#7]
Hi, I'm trying to run GuPPy directly on my C drive on Windows because unfortunately I have a space in my username. I have installed it in the C drive, but when I run the GUI, it defaults to search for files only within my user folder, and fails due to the whitespace. Is there a way to analyze data from the C drive? Thanks!

**Comment by venus-sherathiya** [comment]
sorry for late reply !! 
are you using the most recent version of GuPPy ?

**Comment by alexritger** [comment]
No problem! I believe I have the latest version as I installed the same day I posted the question. I did end up changing my username to remove the space, and it appears to be working fine now. So you can feel free to close this issue unless you think it would be useful for others.

**Comment by venus-sherathiya** [comment]
Awesome !! I will close this issue. Please reach out to me if you have any other issues in the future.
