### ISSUE TITLE
read data

### ISSUE THREAD

**Issue by samjadot** [LernerLab/GuPPy#71]
i'm following all the steps up to raw data but here's what's displayed in the terminals. what should i do? 
![Capture d’écran 2024-02-12 à 12 59 52](https://github.com/LernerLab/GuPPy/assets/157792111/287cfeea-7d88-4a09-a62b-78db001dde86)
here is files FU, MU and the store list
[FU.csv](https://github.com/LernerLab/GuPPy/files/14238038/FU.csv)
[MU.csv](https://github.com/LernerLab/GuPPy/files/14238039/MU.csv)
[StoresListing.txt](https://github.com/LernerLab/GuPPy/files/14238040/StoresListing.txt)

**Comment by venus-sherathiya** [comment]
This is correct !! Nothing is wrong here

**Comment by samjadot** [comment]
oh nice thanks you, but i have a other issue when i click on "PSTH computing" here is de scrips
![1707908133572](https://github.com/LernerLab/GuPPy/assets/157792111/6d17bca8-c73b-4d84-bf4e-3d12cee00198)
Thanks for all your help

**Comment by samjadot** [comment]
![1707908292813](https://github.com/LernerLab/GuPPy/assets/157792111/cf381e80-a393-496c-9d4d-32c3ab8c6ed6)

**Comment by samjadot** [comment]
it is ok, it works now, thanks a lot

**Comment by venus-sherathiya** [comment]
issue resolved !!
