### ISSUE TITLE
Visualization issue

### ISSUE THREAD

**Issue by Helisane** [LernerLab/GuPPy#72]
Hi, I'm a very beginner with fiber photometry and python. Thank you very much for this tool which will make my life easier with starting fiber photometry. 
I've record GrabDA2m in mice in freely mooving in an openfield without watching any specific behavior. I just wanted to see if I can record a decrease of DA after injection of C21 in my mice which are injected with both GrabDA and DREADDs inhibitor. 

I've succeed all the steps of the guppy analysis but i can't open the visualization tool. I obtain this error message in my prompt : 

"There are no behavior event TTLS present to visualization"

Is it not possible to just analyse dopaminergic signal ? I've just my injection as "behavior". 
Thank you.

**Comment by venus-sherathiya** [comment]
Are you getting any error in Step 5 ? Please look for it in the terminal window
Also, can you please send me your storeslist.csv file ?

**Comment by Helisane** [comment]
No, there is no error in step 5 in the terminal window.
[storesList.csv](https://github.com/LernerLab/GuPPy/files/14271194/storesList.csv)

**Comment by venus-sherathiya** [comment]
As per your storeslist file, I cannot see any behavior TTLs. The Visualization GUI revolves around TTL timestamps. If you do not have TTLs, you still get many information in GuPPy. You can find whatever you get in the output folder.

**Comment by Helisane** [comment]
I don't have any behavior. I just have one event, the injection of C21 to inhibit DA release with DREADDs. How can I add this information ?

**Comment by venus-sherathiya** [comment]
If you have the correct timings of the injection, you can create a csv file with the timestamps. The file format should look like [Sample_TTL.csv ](https://drive.google.com/drive/folders/1wODHMpoStIg2ZHmlH5zJhakYDCicmc8A) file

**Comment by Helisane** [comment]
Thank you very much for your answer.

**Comment by Helisane** [comment]
I have added a TTL file but the step 5 doesn't work anymore now. I don't understand. Here the sreenshot of the prompt window, the added file and the storeslist file.
![image](https://github.com/LernerLab/GuPPy/assets/48758547/6247aced-22db-47a2-b99d-d2069c8228e4)
[storesList.csv](https://github.com/LernerLab/GuPPy/files/14271445/storesList.csv)
[sample_TTL.csv](https://github.com/LernerLab/GuPPy/files/14271447/sample_TTL.csv)

**Comment by venus-sherathiya** [comment]
In the PSTH parameters, there are two options 1) Seconds before 0 and 2) Seconds after 0
Their default values are -10 and 20 respectively. Close guppy and relaunch it. After relaunching, set those parameters to -5 and 10 respectively and rerun Step 5. Please let me know if still get the same error

**Comment by Helisane** [comment]
It's working thank you very much.

**Comment by venus-sherathiya** [comment]
issue resolved !!
