### ISSUE TITLE
Problem With Initiating the GUI

### ISSUE THREAD

**Issue by nathanyalross** [LernerLab/GuPPy#73]
Hello, I am having problems pulling GuPPy up after installation. I have followed the instructions outlined in the GuPPy page, and I have tried re-installing the program, but when I get to the final step to pull up the GUI I get the following error:

(guppy) C:\Users\rossnad\Desktop\GuPPy-main>panel serve --show GuPPy/savingInputParameters.ipynb
Script file 'C:\Users\rossnad\AppData\Local\anaconda3\envs\guppy\Scripts\panel-script.py' is not present.

**Comment by venus-sherathiya** [comment]
Can you please execute the command and send me the screenshot of the output ?
`conda info --envs`

**Comment by nathanyalross** [comment]
![Capture](https://github.com/LernerLab/GuPPy/assets/151550032/5556e9de-81b1-4b08-8426-077a4bf96b09)

**Comment by venus-sherathiya** [comment]
Please execute this command
`conda info --envs`

**Comment by venus-sherathiya** [comment]
can you please try to launch guppy using the instructions on Github ? Do you still get the same error ?
Please let me know about it

**Comment by nathanyalross** [comment]
That seemed to have resolve the issue. Sorry, I thought that the updating and specifying folder path would not have been necessary. 
![image](https://github.com/LernerLab/GuPPy/assets/151550032/e3a5b0e0-9dab-4baa-bc1e-0fc599fc4978)

**Comment by venus-sherathiya** [comment]
Please let me know if you have any other issues. Closing this issue for now !!
