### ISSUE TITLE
Open storenames GUI error

### ISSUE THREAD

**Issue by CM242** [LernerLab/GuPPy#76]
Hello,

When i try to open the storenames GUI (step 2) it will not open and i have the below error in the comand window:

Key error: "['time(s)'] not found in axis "

Please could you advise?

Thank you 

![Storename error](https://github.com/LernerLab/GuPPy/assets/157700612/2195580c-5a68-4c93-8e7a-63d860521428)

**Comment by venus-sherathiya** [comment]
Can I please see the screenshot of your raw data files which you are using for analysis ?

**Comment by CM242** [comment]
Thank you for your help, these are the files:

![image](https://github.com/LernerLab/GuPPy/assets/157700612/93409033-0ae8-493c-9e84-d7f8dbf835fc)

**Comment by venus-sherathiya** [comment]
I wanna see the screenshot of the files AA, FU, MU, WTR. If you have more csv files can I please see the screenshots for all of them ?

**Comment by venus-sherathiya** [comment]
closing issue because no further activity
