### ISSUE TITLE
Help to analyse doric files. 

### ISSUE THREAD

**Issue by PedrosoJAB** [LernerLab/GuPPy#77]
Hi, hope if someone could help me.
I opened my Doric file on the Guppy and on the step 2 (Open storenames) gave me those options to me:
AIN01XAOUT01-lockIn
AIN02XAOUT01-lockIn
AIN02XAOUT02-lockIn
AIN01
AIN02
AOUT01
AOUT02

the channel 1 is 470nm (interest)  channel 2 is the 405nm (isosbestic).

But I don't know which one of these options should I use for the analysis  neither what names_for_storenames I should use. 

I am a beginner of this type of analysis and don't have to much experience with that.

Thanks.

**Comment by venus-sherathiya** [comment]
AIN01XAOUT01-lockIn
AIN02XAOUT01-lockIn
AIN02XAOUT02-lockIn
AIN01
AIN02
AOUT01
AOUT02

Out of the options above, you should be able to know which one is 470 and which one is 405. If you open your file you will get an idea. If someone else has recorded the data, that person should know as well.  Is your doric file with 'csv' extension or 'doric' extension ?

**Comment by PedrosoJAB** [comment]
Hi, here it goes. They are the variables that I need for the analysis. 

AINO1 X AOUT1 = 470

AIN02 X OUT2 = 405

With this in mind, I wonder what names_for_storenames I should use for these two variables. My doric file is with 'doric extension' (no csv).

Thanks

**Comment by venus-sherathiya** [comment]
You should follow the naming convention instructions. It is provided on the left side when you open Storenames GUI. If you are not able to follow the instructions, I can try to explain here. 

In your case, you select AINO1 X AOUT1 and AIN02 X OUT2 and then click on "Select Storenames" button. It will pop a new window, where you select appropriate options.

**Comment by PedrosoJAB** [comment]
Hi, I ran my data and then this is what it looks like. 
I would like help to filter it, for example, how to eliminate this period that the signal was down (-4,-5) between my transients.  I don't know what parameter should I change.

Also, when I ran the `visualization` this error showed up. ` 2024-04-17 16:15:01,145 ←[1mThere are no behavior event TTLs present to visualize.←[0m
←[1mThere are no behavior event TTLs present to visualize.←[0m. 
How can I handle this,

Thanks. 
![Figure_M5](https://github.com/LernerLab/GuPPy/assets/158103856/832efec9-fd80-4a87-9215-6cb1e26d3155)
![Figure_1](https://github.com/LernerLab/GuPPy/assets/158103856/c06ef7d2-32e1-45ae-ab20-f52ccdcc0a3e)

**Comment by venus-sherathiya** [comment]
Were you able to find a fix with your data ? If not, please let me know

**Comment by venus-sherathiya** [comment]
Sorry for late response !! I was looking through the issues and I realized that I did not answer your question. Were you able to solve the issue ? Is there any way I can help ? Please let me know

**Comment by venus-sherathiya** [comment]
Closing this issue because no further activity
