### ISSUE TITLE
Group Analysis IndexError

### ISSUE THREAD

**Issue by cnikjou** [LernerLab/GuPPy#78]
I am trying to run a group analysis on two recordings. I've ran the individual files separately, as they both have output folders. But, when I try to run them together through PSTH, I get the following error:

<img width="1198" alt="image" src="https://github.com/LernerLab/GuPPy/assets/158687122/72418785-e79d-447f-9db3-c7a795cef537">
<img width="955" alt="image" src="https://github.com/LernerLab/GuPPy/assets/158687122/e1c29b13-1f77-4f4d-86cf-3e5ff9157e08">

**Comment by venus-sherathiya** [comment]
Can I please see screenshots of storeslist.csv file from both the folders ?

**Comment by cnikjou** [comment]
The first screenshot is the "22-243 Saline" Folder and the second is the "22-243 Quinpirole" Folder

<img width="1194" alt="image" src="https://github.com/LernerLab/GuPPy/assets/158687122/7489a87b-9c66-436b-aa27-5f64977a16bc">

<img width="1199" alt="image" src="https://github.com/LernerLab/GuPPy/assets/158687122/dcc9aed3-4115-4208-ac85-9ad655e2bb22">

**Comment by venus-sherathiya** [comment]
The storeslist files look fine. Is it okay for you to send me your data along with your output folders ?

**Comment by cnikjou** [comment]
Just sent via email

**Comment by venus-sherathiya** [comment]
Addressed the issue !! Problem was storeslist.csv file was not consistent across the group
