### ISSUE TITLE
Baseline z-score

### ISSUE THREAD

**Issue by Helisane** [LernerLab/GuPPy#79]
Hi, 
I would like to try the baseline z-score but I don't understand how to manage the window baseline parameters and I have an issue in the extract timestamps step 
Exception: Baseline Window Parameters for baseline z-score computation zscore_method                                   are not correct.
Can you explain how to do that ? 
thank you,

**Comment by venus-sherathiya** [comment]
what parameters are you using in the screenshot I attached here ?

<img width="363" alt="Screenshot 2024-03-18 at 9 51 21 AM" src="https://github.com/LernerLab/GuPPy/assets/32345130/4e15a6b4-84c9-462d-8a32-1a456f72e642">

**Comment by Helisane** [comment]
At now nothing, that's why I ask for more detail. I don't know what parameters I have to use. I use a TTL for an injection point. So I set the point of injection as time 0. So, for the parameters, do I have to use negative time (before the event point) or a positive time if it's independent of the event ? do I have to take consideration of the 1s deleted at the beginning of the record ? 
Thank you !

**Comment by Helisane** [comment]
I record for 5min in baselin before my injection. Ok I will try. Thank you

**Comment by venus-sherathiya** [comment]
If this answered your question and your analysis worked well, can I please close this issue ?

**Comment by venus-sherathiya** [comment]
issue resolved because no further activity
