### ISSUE TITLE
Error: Only chunked datasets can be resized

### ISSUE THREAD

**Issue by marquardt-k-phd** [LernerLab/GuPPy#8]
Hello,

I am working through GuPPY using the sample CSV data files and have run into the Type Error: Only chunked datasets can be resized when I try to 'Correct timestamps and it's correction'. 

Sample data files are stored in a folder under my user name on the C: drive. 

I've tried multiple input parameters, including the defaults, but always get this error. 

Here is a link to an image with a snapshot of the Anaconda Prompt with the error. 
https://user-images.githubusercontent.com/57728387/152023014-54e71753-c03c-495a-9239-b5de3de412f8.png

**Comment by venus-sherathiya** [comment]
is sample data stored in external hard drive ?
if not, can you try deleting the output folder and run the analysis again from the start ?

**Comment by venus-sherathiya** [comment]
The error you are getting is already being handled in GuPPy.  But you are still getting it. It is weird !!
Can we please meet on zoom so that I can help you better ?
My email id is venus.sherathiya@northwestern.edu. Please reach out to me and we can schedule a time for a meeting.

**Comment by venus-sherathiya** [comment]
While performing step 2 in the analysis process, please use names other than "storenames" in "names_for_storenames"

**Comment by venus-sherathiya** [comment]
While performing step 2 in the analysis process, please use names other than "storenames" in "names_for_storenames"

**Comment by venus-sherathiya** [comment]
While performing step 2 in the analysis process, please use names other than "storenames" in "names_for_storenames"
