### ISSUE TITLE
data analyse

### ISSUE THREAD

**Issue by samjadot** [LernerLab/GuPPy#81]
Hi,
When i have this graph after group analyse, what does the light blue around the mean signify? And is it possible to calculate an average value (a baseline) for each of the selected windows with this graph?
Thanks you very much
![Capture d’écran 2024-03-21 à 10 55 11](https://github.com/LernerLab/GuPPy/assets/157792111/c00997f6-eae0-4ade-9829-53b5308020e1)
![Capture d’écran 2024-03-21 à 10 58 47](https://github.com/LernerLab/GuPPy/assets/157792111/8abf5335-61de-4497-a0ac-0d204132ae26)

**Comment by samjadot** [comment]
what does the light blue around the mean signify? the SEM? the SD?

**Comment by venus-sherathiya** [comment]
Light blue represents SEM

**Comment by venus-sherathiya** [comment]
Can I close this issue, if I resolved your query ?

**Comment by venus-sherathiya** [comment]
mean is the peak value in the mean trial. if you look the mean trial in the visualization GUI, it will match the value to 22.070202.

**Comment by samjadot** [comment]
Ok thank you very much for your help😊 
You Can close this issue now

**Comment by venus-sherathiya** [comment]
issue resolved !!
