### ISSUE TITLE
Save Input Parameters In Step  1

### ISSUE THREAD

**Issue by cy0801** [LernerLab/GuPPy#82]
Hi! I am new to GuPPy and try to use it to analyze my own CSV data. When I select my file(TST1.csv) to right box and click "Save to file", I feel nothing happen in home page. 
![螢幕擷取畫面 2024-04-08 004239](https://github.com/LernerLab/GuPPy/assets/166319894/984965dc-97b6-412d-b23e-871118468dce)
![螢幕擷取畫面 2024-04-08 004514](https://github.com/LernerLab/GuPPy/assets/166319894/713739a9-e442-43ee-a742-0b0f31ccb7f4)

So, I want to do step 2 and click"Open Storenames GUI", there isn't file I can choose. 

![螢幕擷取畫面 2024-04-08 004418](https://github.com/LernerLab/GuPPy/assets/166319894/ab690980-d2e5-49ad-86ea-841cbb75c3eb)

I really what to know whether i do something wrong. There are screenshots about my system pages and raw data.

![螢幕擷取畫面 2024-04-08 004144](https://github.com/LernerLab/GuPPy/assets/166319894/0fbb76d6-1625-489d-abdf-2f78528b2293)
![螢幕擷取畫面 2024-04-08 004206](https://github.com/LernerLab/GuPPy/assets/166319894/2e9fa311-c63b-4bf9-b255-ae494f3cd9bb)
![螢幕擷取畫面 2024-04-08 004611](https://github.com/LernerLab/GuPPy/assets/166319894/96973c53-6ba5-4c42-9497-48fe83c3eab7)

**Comment by venus-sherathiya** [comment]
You should your files for a particular recording session in a folder and select that folder for the analysis. This is solve your problem

**Comment by cy0801** [comment]
Okay, I will try again. Thank you.

**Comment by venus-sherathiya** [comment]
If it worked for you, can I please close the issue ?

**Comment by cy0801** [comment]
Yes, it worked, thank you very much. But now I have another trouble in Step 2, Should I raise another issue？

**Comment by venus-sherathiya** [comment]
Please post your issue over here !!

**Comment by cy0801** [comment]
I can do step1 now, but I can not do step4. Below photo is my raw data screenshot
![螢幕擷取畫面 2024-04-20 200734](https://github.com/LernerLab/GuPPy/assets/166319894/1232bb61-789a-47d6-88b9-bac239923885)

I want to know whether my file form can not fit the system so that I can not analyse, or I can do something to fix it.

**Comment by venus-sherathiya** [comment]
what system do you use for data recording (Doric, NPM, TDT  etc) ?

**Comment by cy0801** [comment]
I use RWD R811 Dual Color Multichannel Fiber Photometry System for my experiments, but I don't know which system(Doric, NPM, TDT etc) for data recording (Doric, NPM, TDT etc)
![螢幕擷取畫面 2024-04-24 151622](https://github.com/LernerLab/GuPPy/assets/166319894/7f870fbf-7844-4057-a1fd-d59b17fb093c)

**Comment by venus-sherathiya** [comment]
Actually, we do not support data recorded from these systems. You can convert your data to csv format which GuPPy supports and do the analysis. If you have any questions about it, I am happy to do a zoom call with you and guide you with it.
