### ISSUE TITLE
extract timestamps

### ISSUE THREAD

**Issue by samjadot** [LernerLab/GuPPy#83]
Hi,
On this graph, what does the y-axis represent? 
![Capture d’écran 2024-04-09 à 12 30 08](https://github.com/LernerLab/GuPPy/assets/157792111/7aec4018-0007-4a63-946a-99daaf372fee)

**Comment by venus-sherathiya** [comment]
It should be the same unit as your raw data unit.

**Comment by venus-sherathiya** [comment]
issue resolved !!
