### ISSUE TITLE
Visualize issue when doing group analysis

### ISSUE THREAD

**Issue by AliceChangYaGin** [LernerLab/GuPPy#84]
Hi! I am new to GuPPy, thank you for this tool and all the issues arise here, it's helpful to see all these discussions and how people got their problem solved.  

I'm recording using TDT system, two channel (405 for Isosbestic Control and 465 for signal) were introduced for my analysis. Every recording, two pods were connected to two individual mice. I split the data to two files and did individual analysis separately and that works well. However, I encounter a problem when trying to use group analysis. Prompt showed “There are no behavior event TTLs present to visualize.” I attach the screen shots here. 

![guppy issue-7](https://github.com/LernerLab/GuPPy/assets/166543019/2a43bec9-3052-4d38-be25-945cfe6df0ca)
![guppy issue-8](https://github.com/LernerLab/GuPPy/assets/166543019/09ac9a41-5622-436f-a0ed-4c94c3a5d25a)

And here are the screen shots of the files I used for individual analysis. 

![guppy issue-2](https://github.com/LernerLab/GuPPy/assets/166543019/78d7e911-bc3f-4e4e-bc15-7c348d513831)

I don’t have any behavior TTL during the recording. Instead, I created a csv file to mark the exact timestamps for my drug injection, as the screen shot shown. 

![guppy issue-3](https://github.com/LernerLab/GuPPy/assets/166543019/1c0e7eb3-2ce9-4980-a2cf-7c9b1fc73d45)

Can anyone give me suggestions to solve this problem? 

Thank you!
Alice

**Comment by venus-sherathiya** [comment]
Are you setting "Visualize Average Results?" parameter to TRUE before opening visualization GUI ?

**Comment by AliceChangYaGin** [comment]
Hi, 
Yes, I did. Here is my screen shot
![guppy issue-9](https://github.com/LernerLab/GuPPy/assets/166543019/5a61dfec-af7f-4cb6-b77d-0b92f6c5081c)

**Comment by venus-sherathiya** [comment]
Is it possible for you to send me the folders Animal17 and Animal18 ? If yes, please upload it on a drive and share it with me at venus.sherathiya@northwestern.edu.
I will try myself and see what's the issue

**Comment by AliceChangYaGin** [comment]
Hey, I have send you an email containing the link for those folders. Thank you again for the help!

**Comment by venus-sherathiya** [comment]
Hello,

I am so sorry for the late response. The data you submitted to me does not show any issues. It is able to do the average and I can also visualize the average results. Are you still facing the same issue ?

**Comment by venus-sherathiya** [comment]
issue resolved because no further activity
