### ISSUE TITLE
open storenames "KeyError: "['Time(s)'] not found in axis" 

### ISSUE THREAD

**Issue by Ninoharaa** [LernerLab/GuPPy#87]
I generated a .csv from Doric and I'm not able to open the storenames GUI for the mentionned error, even if I changed "timestamps" and "data" as head columns from the previous ones.

**Comment by venus-sherathiya** [comment]
Can we please do a zoom call so that I can help you better ?

**Comment by Ninoharaa** [comment]
Hi, it would be perfect, thank you.
Are you available on next Monday, 10th ?

Best,
Sophie Younes

Le jeu. 6 juin 2024 à 17:03, Venus Sherathiya ***@***.***> a
écrit :

**Comment by venus-sherathiya** [comment]
Can you please send me your availability for June 10th at venus.sherathiya@northwestern.edu ?

**Comment by venus-sherathiya** [comment]
closing issue because no further activity
