### ISSUE TITLE
Access traces to Calculate AUC

### ISSUE THREAD

**Issue by madeleinemm** [LernerLab/GuPPy#89]
Hi there,
  First, thank you for creating GuPPy, it is such helpful software! I was wondering how I can access the data files for the photometry traces. I want to be able to calculate the area under the curve for different timepoints across the aligned traces so I just need access to the values being plotted.
Thank you!

**Comment by venus-sherathiya** [comment]
What do you mean by photometry traces ? Do you mean signal channel raw trace ?

**Comment by madeleinemm** [comment]
I mean the averaged signal aligned to an event - the values being plotted in the visualization. Thanks!

**Comment by venus-sherathiya** [comment]
You can read the file with the name "*_z_score_*.h5". The event aligned trials (along with the average) is stored in this file. I have sample code in the GuPPy folder to read this file in Python and Matlab. Please let me know if you have any other questions

**Comment by venus-sherathiya** [comment]
Closing issue because no further activity
