### ISSUE TITLE
Storenames GUI 

### ISSUE THREAD

**Issue by kai-price** [LernerLab/GuPPy#9]
Hello,

The instructions up to this point have been great. This issue is similar to a previous question. I plan to use Neurophotometrics so I used the Neurophotometrics sample data in the Box. I got up to choosing input parameters, but I cannot choose storenames- the dropdown says "no choices to choose from".  When I select "open storenames GUI" there is no error in the terminal. What is causing this problem?

**Comment by venus-sherathiya** [comment]
Can I please see a screenshot of the window where the dropdown says "no choices to choose from" ?

**Comment by venus-sherathiya** [comment]
have you seen this tutorial video https://www.youtube.com/watch?v=n1HSGRnBYPQ ?
if yes, are you following the exact steps shown in the video ?

**Comment by venus-sherathiya** [comment]
Hello, 
Were you able to solve the error ?

**Comment by kai-price** [comment]
Yes, I was able to solve the issue. Thank you!
