### ISSUE TITLE
Isobestic control changing after removal of artefacts

### ISSUE THREAD

**Issue by laura9130** [LernerLab/GuPPy#90]
In my photometry trace, we had some artefacts that I had to remove manually as GUPPY wasn't removing them all. However, after I manually removed the artefacts and ran it again, the isobestic channel would become much more active and affect my analysis windows. Anyone have any idea why? It didn't happen when I didn't remove the artefacts either side of the peak. 
![artefacts removed](https://github.com/user-attachments/assets/da7a03e7-7003-4b1e-9ccb-2b68f1e6be3e)
![original trace](https://github.com/user-attachments/assets/b876b8cb-3814-4e0a-ba87-3772589151d6)

**Comment by venus-sherathiya** [comment]
GuPPy has a feature to remove artifacts. You need to select chunks of data which looks good and GuPPy will take care of it. That feature is not working well ?

**Comment by laura9130** [comment]
> GuPPy has a feature to remove artifacts. You need to select chunks of data which looks good and GuPPy will take care of it. That feature is not working well ?

Sorry the images are in the wrong order. So when I would manually remove those chunks, the isobestic control channel suddenly went from flat to having a peak, which affected my peak and AUC for that event. Only happened with this animal, not with others

**Comment by venus-sherathiya** [comment]
If possible, can you please send me this data along with the output folder for this data ?

**Comment by venus-sherathiya** [comment]
No further activity. So, closing this issue
