### ISSUE TITLE
Issue in Step 4 

### ISSUE THREAD

**Issue by jazzafterdark92** [LernerLab/GuPPy#91]
Hello Guppy Development Team,
I am encountering an issue in Step 4 of the pipeline, and I am receiving the following error message (attached). My behavioral and signal timestamps are already in seconds. Could this be causing the problem? Could you please assist in debugging this error?
Thank you! 
<img width="958" alt="Screenshot 2024-08-07 at 11 18 22" src="https://github.com/user-attachments/assets/c5fee5ba-74db-4354-897f-80dc3213abd9">

**Comment by venus-sherathiya** [comment]
Can I please see the screenshot of the storeslist.csv file which gets saved in the output folder ?

**Comment by jazzafterdark92** [comment]
<img width="590" alt="Screenshot 2024-08-21 at 19 40 17" src="https://github.com/user-attachments/assets/e5b1a9bd-8347-4758-b6ed-4e58cd8244ea"> 
Sure please find it attached! Sorry for the delayed response

**Comment by venus-sherathiya** [comment]
When you do Step 2, please follow the instructions for storing storeslist.csv file mentioned on the left side of the page. 
Naming convention should be followed properly.
Please let me know if you have any questions.

**Comment by jazzafterdark92** [comment]
Thanks I managed to make it work!
