### ISSUE TITLE
Detect downward peaks

### ISSUE THREAD

**Issue by MannyEsguerra** [LernerLab/GuPPy#92]
Is there a built in way to detect negative-going peaks in GuPPy, either by inverting the signal or with thresholding?

**Comment by venus-sherathiya** [comment]
you mean negative peaks in z-score trace ?

**Comment by MannyEsguerra** [comment]
Does GuPPy only detect positive-going peaks In the signal_xxx ?

**Comment by venus-sherathiya** [comment]
yes, it only detects positive-going peaks in signal_xxx. You can try inverting the signal and see what it works. But I am not sure how good will it work

**Comment by MannyEsguerra** [comment]
Is there a way to invert a signal inside Guppy?

**Comment by venus-sherathiya** [comment]
Unfortunately, there it not. You can write your own small piece of code to do that
