### ISSUE TITLE
Cannot run Step 3 to read raw data

### ISSUE THREAD

**Issue by h1408** [LernerLab/GuPPy#94]
Hi, I am trying to use guppy to analyze some data without using the 405 channel data from the TDT stream. When inputting parameters, I selected "False" for "Isosbestic Control Channel? (bool)" and input the storenames. I tried to run Step 3 and got the following error. I have not seen this before and am not sure how to remedy it. I have run guppy before without a control channel and have not encountered this error before. Any insight would be greatly appreciated! 

```
Trying to read tsq file.
Data from tsq file fetched.
Reading data for event 465A ...
Reading data for event Note ...
Data for event Note fetched and stored.
Reading data for event cntrl0 ...
Requested store name cntrl0 not found (case-sensitive).
File contains the following TDT store names:
['1___' '2-1_' '2___' '405A' '465A' 'Cam1' 'Fi1i' 'Fi1r' 'Note']
TDT store name cntrl0 not found.
Trying to read data for cntrl0 from csv file.
Data for event 465A fetched and stored.
Read progress bar increment values stopped.
multiprocessing.pool.RemoteTraceback: 


[...]

Exception: No csv file found for event cntrl0



```

**Comment by h1408** [comment]
Hi yes I can do that! Can I send it via email?

**Comment by venus-sherathiya** [comment]
yes. Please send me at venus.sherathiya@northwestern.edu

**Comment by venus-sherathiya** [comment]
issue resolved !!
