### ISSUE TITLE
Guppy not loading

### ISSUE THREAD

**Issue by laura9130** [LernerLab/GuPPy#96]
When trying to open Guppy, the window will just stay stuck on the loading screen. No errors showing up in the conda window
<img width="815" alt="guppy loading screen" src="https://github.com/user-attachments/assets/0417c468-01d8-4748-9589-32c4b83a2a78">

**Comment by MannyEsguerra** [comment]
At this point you should be seeing this dialog window. The program will wait until you have clicked "Select a Folder" and selected a data directory. 

![image](https://github.com/user-attachments/assets/e722369d-2239-4cd9-b364-10fcc3453efa)

**Comment by laura9130** [comment]
I think that's for the new version, I'm working with the older version. I don't have that pop up

> At this point you should be seeing this small dialog window. The program will wait until you have clicked "Select a Folder" and selected a data directory.
> 
> ![image](https://private-user-images.githubusercontent.com/46828260/368172215-e722369d-2239-4cd9-b364-10fcc3453efa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2Mzg2MjMsIm5iZiI6MTcyNjYzODMyMywicGF0aCI6Ii80NjgyODI2MC8zNjgxNzIyMTUtZTcyMjM2OWQtMjIzOS00Y2Q5LWIzNjQtMTBmY2MzNDUzZWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA1NDUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwOGNjMDM3NTIxZDdhNDg4ODJhYTZjYmY5ZjJmZmI2OWM1ZDE2Mzk0MzliMjIyOWExNDBhMDZlMDU5ZjVkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PzXX2Scj92ICbCVupc9eGf5Eowe4p7Ay2-9vxTVkuwc)

**Comment by venus-sherathiya** [comment]
Were you able to solve your issue ? Please let me know

**Comment by venus-sherathiya** [comment]
Closing issue because of no response
