### ISSUE TITLE
 Storenames GUI - storename duplication error in .doric file

### ISSUE THREAD

**Issue by baris-61** [LernerLab/GuPPy#99]
![Capture](https://github.com/user-attachments/assets/8dfedd6c-36bb-46db-8eeb-bd71cb546787)
problem is at ROI01,ROI02,ROI03 these files are control and signal data, when doric opens these files, ROI01,ROI01 names becomes ROI1 - (CAM1 EXC1) and ROI1 - (CAM1 EXC2).
I cant select only one of the signals (auto selects both) and creates single store name.
Store names to repeat doesnt fix my problem due to there are 2 data in single storename.
If I use Storenames to repeat I get this error:
  File "C:\Users\baris\Desktop\GuPPy-main\GuPPy\readTevTsq.py", line 445, in access_data_doricV6
    raise Exception('More than one string matched (which should not be the case)')
Exception: More than one string matched (which should not be the case)

**Comment by venus-sherathiya** [comment]
Can we please schedule a zoom call to help you with your problem ? If yes, please send me your availability at venus.sherathiya@northwestern.edu

**Comment by venus-sherathiya** [comment]
Issue addressed and solved !!
